import { conjugate, conjugateReading, ConjugationForm, VerbData } from '../utils/conjugate';
import { getExampleSentence } from '../utils/formExamples';
import n5 from '../data/formExamples.n5.json';
import n4 from '../data/formExamples.n4.json';
import n3 from '../data/formExamples.n3.json';
import n2 from '../data/formExamples.n2.json';
import verbsJson from '../data/verbs.json';

const verbs = verbsJson as Record<string, VerbData>;
const dataset = n5 as Record<string, Partial<Record<ConjugationForm, string>>>;
const exampleForms: ConjugationForm[] = [
  'masu',
  'te',
  'ta',
  'nai',
  'potential',
  'passive',
  'causative',
  'conditional_ba',
  'conditional_tara',
  'volitional',
  'imperative',
];

function expectExcludedFormsAbsent(
  level: VerbData['jlpt'],
  examples: Record<string, Partial<Record<ConjugationForm, string>>>,
) {
  for (const [verb, data] of Object.entries(verbs)) {
    if (data.jlpt !== level) continue;
    for (const form of data.excludeForms || []) {
      expect(examples[verb]?.[form]).toBeUndefined();
      expect(getExampleSentence(verb, form)).toBeUndefined();
    }
  }
}

function nonExcludeOmissions(
  level: VerbData['jlpt'],
  examples: Record<string, Partial<Record<ConjugationForm, string>>>,
): [string, ConjugationForm][] {
  const omissions: [string, ConjugationForm][] = [];
  for (const verb of Object.keys(examples)) {
    const data = verbs[verb];
    if (!data || data.jlpt !== level) continue;
    const excluded = new Set(data.excludeForms || []);
    for (const form of exampleForms) {
      if (!excluded.has(form) && !examples[verb]?.[form]) {
        omissions.push([verb, form]);
      }
    }
  }
  return omissions;
}

const expectedCountsByForm: Partial<Record<ConjugationForm, number>> = {
  masu: 120,
  te: 120,
  ta: 120,
  nai: 119,
  potential: 96,
  passive: 70,
  causative: 99,
  conditional_ba: 118,
  conditional_tara: 120,
  volitional: 97,
  imperative: 99,
};

const intentionalOmissions: [string, ConjugationForm][] = [
  ['ある', 'potential'],
  ['ある', 'passive'],
  ['ある', 'causative'],
  ['ある', 'volitional'],
  ['ある', 'imperative'],
  ['遊ぶ', 'passive'],
  ['泳ぐ', 'passive'],
  ['渡る', 'passive'],
  ['鳴る', 'passive'],
  ['止まる', 'passive'],
  ['困る', 'passive'],
  ['頑張る', 'passive'],
  ['結婚する', 'passive'],
  ['電話する', 'passive'],
  ['洗濯する', 'passive'],
  ['勉強する', 'passive'],
  ['料理する', 'passive'],
  ['答える', 'passive'],
  ['鳴る', 'causative'],
  ['飛ぶ', 'causative'],
  ['動く', 'causative'],
  ['なくす', 'causative'],
  ['差し上げる', 'causative'],
  ['つく', 'volitional'],
  ['つく', 'imperative'],
  ['困る', 'imperative'],
  ['疲れる', 'imperative'],
  ['差し上げる', 'imperative'],
  ['くださる', 'imperative'],
  ['くれる', 'imperative'],
];

describe('N5 form example sentences', () => {
  const entries: [string, ConjugationForm, string][] = [];
  for (const [verb, forms] of Object.entries(dataset)) {
    for (const [form, sentence] of Object.entries(forms)) {
      entries.push([verb, form as ConjugationForm, sentence as string]);
    }
  }

  it('covers a non-trivial number of sentences', () => {
    expect(entries.length).toBeGreaterThan(1000);
  });

  it('matches the expected count by form', () => {
    const counts: Partial<Record<ConjugationForm, number>> = {};
    for (const [, form] of entries) {
      counts[form] = (counts[form] || 0) + 1;
    }
    expect(counts).toEqual(expectedCountsByForm);
  });

  it('only references verbs that exist in the verb list', () => {
    for (const verb of Object.keys(dataset)) {
      expect(verbs[verb]).toBeDefined();
    }
  });

  it('each sentence contains its exact conjugated form (kanji or kana)', () => {
    const offenders: string[] = [];
    for (const [verb, form, sentence] of entries) {
      const data = verbs[verb];
      const kanji = conjugate(verb, data, form).value;
      const kana = conjugateReading(data, form);
      if (!sentence.includes(kanji) && !sentence.includes(kana)) {
        offenders.push(`${verb}:${form} -> "${sentence}" (expected ${kanji}/${kana})`);
      }
    }
    expect(offenders).toEqual([]);
  });

  it('getExampleSentence returns dataset entries and undefined for omitted forms', () => {
    expect(getExampleSentence('食べる', 'volitional')).toContain('食べよう');
    for (const [verb, form] of intentionalOmissions) {
      expect(dataset[verb]?.[form]).toBeUndefined();
      expect(getExampleSentence(verb, form)).toBeUndefined();
    }
    // Unknown verb -> undefined, never throws.
    expect(getExampleSentence('存在しない動詞', 'masu')).toBeUndefined();
  });

  it('generates no examples for N5 excludeForms forms', () => {
    expectExcludedFormsAbsent('N5', dataset);
  });
});

const n4dataset = n4 as Record<string, Partial<Record<ConjugationForm, string>>>;
const n4ExpectedCountsByForm: Partial<Record<ConjugationForm, number>> = {
  masu: 173,
  te: 173,
  ta: 173,
  nai: 173,
  potential: 120,
  passive: 102,
  causative: 143,
  conditional_ba: 173,
  conditional_tara: 173,
  volitional: 131,
  imperative: 145,
};

const n4IntentionalOmissions: [string, ConjugationForm][] = [
  ['届く', 'potential'],
  ['届く', 'passive'],
  ['届く', 'volitional'],
  ['変わる', 'passive'],
  ['変わる', 'causative'],
  ['集まる', 'passive'],
  ['落ちる', 'potential'],
  ['落ちる', 'passive'],
  ['落ちる', 'causative'],
  ['落ちる', 'volitional'],
  ['壊れる', 'potential'],
  ['壊れる', 'passive'],
  ['壊れる', 'causative'],
  ['壊れる', 'volitional'],
  ['直る', 'potential'],
  ['直る', 'passive'],
  ['直る', 'causative'],
  ['直る', 'volitional'],
  ['間に合う', 'potential'],
  ['間に合う', 'passive'],
  ['間に合う', 'volitional'],
  ['間に合う', 'imperative'],
  ['続く', 'potential'],
  ['続く', 'passive'],
  ['続く', 'volitional'],
  ['続く', 'imperative'],
  ['増える', 'potential'],
  ['増える', 'passive'],
  ['増える', 'causative'],
  ['増える', 'volitional'],
  ['減る', 'potential'],
  ['減る', 'passive'],
  ['減る', 'causative'],
  ['減る', 'volitional'],
  ['決まる', 'potential'],
  ['決まる', 'volitional'],
  ['込む', 'potential'],
  ['込む', 'passive'],
  ['込む', 'causative'],
  ['込む', 'volitional'],
  ['込む', 'imperative'],
  ['向かう', 'passive'],
  ['触る', 'passive'],
  ['急ぐ', 'passive'],
  ['並ぶ', 'potential'],
  ['並ぶ', 'passive'],
  ['卒業する', 'passive'],
  ['故障する', 'potential'],
  ['故障する', 'passive'],
  ['故障する', 'volitional'],
  ['故障する', 'imperative'],
  ['出発する', 'passive'],
  ['到着する', 'passive'],
  ['賛成する', 'passive'],
  ['反対する', 'passive'],
  ['努力する', 'passive'],
  ['生活する', 'passive'],
  ['引っ越す', 'passive'],
  ['悲しむ', 'potential'],
  ['悲しむ', 'volitional'],
  ['悲しむ', 'imperative'],
  ['迷う', 'potential'],
  ['迷う', 'passive'],
  ['迷う', 'volitional'],
  ['迷う', 'imperative'],
  ['治る', 'potential'],
  ['治る', 'passive'],
  ['治る', 'causative'],
  ['治る', 'volitional'],
  ['濡れる', 'potential'],
  ['濡れる', 'passive'],
  ['濡れる', 'volitional'],
  ['濡れる', 'imperative'],
  ['願う', 'causative'],
  ['遅れる', 'potential'],
  ['遅れる', 'passive'],
  ['遅れる', 'volitional'],
  ['遅れる', 'imperative'],
  ['間違える', 'imperative'],
  ['慣れる', 'passive'],
  ['似合う', 'potential'],
  ['似合う', 'passive'],
  ['似合う', 'causative'],
  ['似合う', 'volitional'],
  ['似合う', 'imperative'],
  ['驚く', 'potential'],
  ['驚く', 'volitional'],
  ['起こる', 'potential'],
  ['起こる', 'passive'],
  ['起こる', 'causative'],
  ['起こる', 'volitional'],
  ['倒れる', 'potential'],
  ['倒れる', 'causative'],
  ['倒れる', 'volitional'],
  ['受かる', 'potential'],
  ['受かる', 'passive'],
  ['受かる', 'volitional'],
  ['感動する', 'passive'],
  ['乾く', 'potential'],
  ['乾く', 'passive'],
  ['乾く', 'causative'],
  ['乾く', 'volitional'],
  ['光る', 'potential'],
  ['光る', 'passive'],
  ['光る', 'volitional'],
  ['太る', 'passive'],
  ['痩せる', 'passive'],
  ['ぶつかる', 'potential'],
  ['ぶつかる', 'causative'],
  ['すれ違う', 'passive'],
  ['すれ違う', 'volitional'],
  ['気をつける', 'passive'],
  ['震える', 'potential'],
  ['震える', 'passive'],
  ['震える', 'volitional'],
  ['震える', 'imperative'],
  ['騙される', 'potential'],
  ['騙される', 'passive'],
  ['騙される', 'causative'],
  ['騙される', 'volitional'],
  ['騙される', 'imperative'],
  ['転がる', 'potential'],
  ['転がる', 'passive'],
  ['浮かべる', 'passive'],
  ['思い付く', 'passive'],
  ['気に入る', 'potential'],
  ['気に入る', 'volitional'],
  ['気に入る', 'imperative'],
  ['役立つ', 'potential'],
  ['役立つ', 'passive'],
  ['役立つ', 'causative'],
  ['役立つ', 'volitional'],
  ['役立つ', 'imperative'],
  ['間違う', 'potential'],
  ['間違う', 'imperative'],
  ['見つかる', 'potential'],
  ['見つかる', 'passive'],
  ['見つかる', 'causative'],
  ['見つかる', 'volitional'],
  ['生まれる', 'potential'],
  ['生まれる', 'passive'],
  ['生まれる', 'causative'],
  ['育つ', 'potential'],
  ['育つ', 'passive'],
  ['育つ', 'causative'],
  ['咲く', 'potential'],
  ['咲く', 'passive'],
  ['咲く', 'volitional'],
  ['混む', 'potential'],
  ['混む', 'causative'],
  ['混む', 'volitional'],
  ['混む', 'imperative'],
  ['訪れる', 'passive'],
  ['訪れる', 'imperative'],
  ['片寄る', 'potential'],
  ['片寄る', 'passive'],
  ['片寄る', 'volitional'],
  ['片寄る', 'imperative'],
  ['怒る', 'potential'],
  ['怒る', 'imperative'],
  ['こぼす', 'potential'],
  ['こぼす', 'volitional'],
  ['こぼす', 'imperative'],
  ['こぼれる', 'potential'],
  ['こぼれる', 'passive'],
  ['こぼれる', 'volitional'],
  ['こぼれる', 'imperative'],
  ['すべる', 'passive'],
  ['つまずく', 'potential'],
  ['つまずく', 'passive'],
  ['つまずく', 'volitional'],
  ['つまずく', 'imperative'],
  ['はしゃぐ', 'passive'],
  ['折る', 'potential'],
  ['割る', 'potential'],
];

describe('N4 form example sentences', () => {
  const entries: [string, ConjugationForm, string][] = [];
  for (const [verb, forms] of Object.entries(n4dataset)) {
    for (const [form, sentence] of Object.entries(forms)) {
      entries.push([verb, form as ConjugationForm, sentence as string]);
    }
  }

  it('covers a non-trivial number of sentences', () => {
    expect(entries.length).toBeGreaterThan(1500);
  });

  it('matches the expected count by form', () => {
    const counts: Partial<Record<ConjugationForm, number>> = {};
    for (const [, form] of entries) {
      counts[form] = (counts[form] || 0) + 1;
    }
    expect(counts).toEqual(n4ExpectedCountsByForm);
  });

  it('only references N4 verbs that exist', () => {
    for (const verb of Object.keys(n4dataset)) {
      expect(verbs[verb]).toBeDefined();
      expect(verbs[verb].jlpt).toBe('N4');
    }
  });

  it('each sentence contains its exact conjugated form (kanji or kana)', () => {
    const offenders: string[] = [];
    for (const [verb, form, sentence] of entries) {
      const data = verbs[verb];
      const kanji = conjugate(verb, data, form).value;
      const kana = conjugateReading(data, form);
      if (!sentence.includes(kanji) && !sentence.includes(kana)) {
        offenders.push(`${verb}:${form} -> "${sentence}" (expected ${kanji}/${kana})`);
      }
    }
    expect(offenders).toEqual([]);
  });

  it('generates no examples for N4 excludeForms forms', () => {
    expectExcludedFormsAbsent('N4', n4dataset);
  });

  it('omits only intentional non-exclude N4 forms', () => {
    expect(nonExcludeOmissions('N4', n4dataset)).toEqual(n4IntentionalOmissions);
  });
});

const n3dataset = n3 as Record<string, Partial<Record<ConjugationForm, string>>>;
const n3ExpectedCountsByForm: Partial<Record<ConjugationForm, number>> = {
  masu: 380,
  te: 379,
  ta: 378,
  nai: 380,
  potential: 269,
  passive: 222,
  causative: 278,
  conditional_ba: 376,
  conditional_tara: 377,
  volitional: 277,
  imperative: 258,
};

const n3IntentionalOmissions: [string, ConjugationForm][] = [
  ['得る', 'causative'],
  ['含む', 'potential'],
  ['含む', 'causative'],
  ['含む', 'volitional'],
  ['含む', 'imperative'],
  ['抱える', 'passive'],
  ['眠る', 'passive'],
  ['戦う', 'passive'],
  ['勝つ', 'passive'],
  ['負ける', 'potential'],
  ['負ける', 'passive'],
  ['負ける', 'volitional'],
  ['負ける', 'imperative'],
  ['揺れる', 'potential'],
  ['揺れる', 'passive'],
  ['揺れる', 'causative'],
  ['揺れる', 'volitional'],
  ['揺れる', 'imperative'],
  ['沈む', 'potential'],
  ['沈む', 'passive'],
  ['沈む', 'causative'],
  ['沈む', 'volitional'],
  ['沈む', 'imperative'],
  ['浮かぶ', 'potential'],
  ['浮かぶ', 'passive'],
  ['浮かぶ', 'causative'],
  ['浮かぶ', 'volitional'],
  ['浮かぶ', 'imperative'],
  ['響く', 'potential'],
  ['響く', 'passive'],
  ['響く', 'volitional'],
  ['響く', 'imperative'],
  ['輝く', 'potential'],
  ['輝く', 'passive'],
  ['輝く', 'volitional'],
  ['輝く', 'imperative'],
  ['匂う', 'potential'],
  ['匂う', 'passive'],
  ['匂う', 'volitional'],
  ['匂う', 'imperative'],
  ['成功する', 'potential'],
  ['成功する', 'passive'],
  ['成功する', 'imperative'],
  ['失敗する', 'potential'],
  ['失敗する', 'passive'],
  ['失敗する', 'volitional'],
  ['失敗する', 'imperative'],
  ['完成する', 'potential'],
  ['完成する', 'passive'],
  ['完成する', 'volitional'],
  ['完成する', 'imperative'],
  ['影響する', 'potential'],
  ['影響する', 'causative'],
  ['影響する', 'volitional'],
  ['影響する', 'imperative'],
  ['存在する', 'potential'],
  ['存在する', 'passive'],
  ['存在する', 'causative'],
  ['存在する', 'volitional'],
  ['存在する', 'imperative'],
  ['活動する', 'passive'],
  ['戻る', 'passive'],
  ['戻る', 'causative'],
  ['進む', 'potential'],
  ['進む', 'causative'],
  ['気付く', 'imperative'],
  ['重なる', 'potential'],
  ['重なる', 'passive'],
  ['重なる', 'causative'],
  ['重なる', 'volitional'],
  ['重なる', 'imperative'],
  ['伸びる', 'potential'],
  ['伸びる', 'passive'],
  ['伸びる', 'causative'],
  ['伸びる', 'volitional'],
  ['伸びる', 'imperative'],
  ['伸ばす', 'passive'],
  ['繋がる', 'potential'],
  ['繋がる', 'passive'],
  ['繋がる', 'causative'],
  ['繋がる', 'volitional'],
  ['繋がる', 'imperative'],
  ['過ぎる', 'potential'],
  ['過ぎる', 'passive'],
  ['過ぎる', 'causative'],
  ['過ぎる', 'volitional'],
  ['過ぎる', 'imperative'],
  ['預かる', 'passive'],
  ['従う', 'passive'],
  ['当たる', 'potential'],
  ['当たる', 'passive'],
  ['当たる', 'causative'],
  ['当たる', 'volitional'],
  ['温まる', 'potential'],
  ['温まる', 'passive'],
  ['温まる', 'causative'],
  ['温まる', 'imperative'],
  ['冷める', 'potential'],
  ['冷める', 'passive'],
  ['冷める', 'causative'],
  ['冷める', 'volitional'],
  ['冷める', 'imperative'],
  ['暮らす', 'passive'],
  ['暮らす', 'imperative'],
  ['叶う', 'potential'],
  ['叶う', 'passive'],
  ['叶う', 'causative'],
  ['叶う', 'volitional'],
  ['叶う', 'imperative'],
  ['悔やむ', 'potential'],
  ['悔やむ', 'causative'],
  ['悔やむ', 'volitional'],
  ['悔やむ', 'imperative'],
  ['抜く', 'potential'],
  ['抜ける', 'potential'],
  ['抜ける', 'passive'],
  ['抜ける', 'causative'],
  ['抜ける', 'volitional'],
  ['抜ける', 'imperative'],
  ['干る', 'potential'],
  ['干る', 'passive'],
  ['干る', 'causative'],
  ['干る', 'volitional'],
  ['干る', 'imperative'],
  ['散る', 'potential'],
  ['散る', 'passive'],
  ['散る', 'causative'],
  ['散る', 'volitional'],
  ['散る', 'imperative'],
  ['染まる', 'potential'],
  ['染まる', 'passive'],
  ['染まる', 'causative'],
  ['染まる', 'volitional'],
  ['染まる', 'imperative'],
  ['積もる', 'potential'],
  ['積もる', 'passive'],
  ['積もる', 'causative'],
  ['積もる', 'volitional'],
  ['積もる', 'imperative'],
  ['汚れる', 'potential'],
  ['汚れる', 'passive'],
  ['汚れる', 'causative'],
  ['汚れる', 'volitional'],
  ['汚れる', 'imperative'],
  ['溜まる', 'potential'],
  ['溜まる', 'passive'],
  ['溜まる', 'causative'],
  ['溜まる', 'volitional'],
  ['溜まる', 'imperative'],
  ['驚かす', 'causative'],
  ['沸く', 'potential'],
  ['沸く', 'passive'],
  ['沸く', 'causative'],
  ['沸く', 'volitional'],
  ['沸く', 'imperative'],
  ['映る', 'potential'],
  ['映る', 'passive'],
  ['映る', 'causative'],
  ['映る', 'volitional'],
  ['映る', 'imperative'],
  ['外れる', 'potential'],
  ['外れる', 'passive'],
  ['外れる', 'causative'],
  ['外れる', 'volitional'],
  ['外れる', 'imperative'],
  ['沿う', 'potential'],
  ['沿う', 'passive'],
  ['沿う', 'causative'],
  ['沿う', 'volitional'],
  ['沿う', 'imperative'],
  ['我慢する', 'passive'],
  ['集中する', 'passive'],
  ['緊張する', 'potential'],
  ['緊張する', 'passive'],
  ['満足する', 'passive'],
  ['後悔する', 'potential'],
  ['後悔する', 'passive'],
  ['後悔する', 'volitional'],
  ['後悔する', 'imperative'],
  ['独立する', 'passive'],
  ['成長する', 'passive'],
  ['成長する', 'imperative'],
  ['加わる', 'passive'],
  ['加わる', 'causative'],
  ['加わる', 'imperative'],
  ['向く', 'passive'],
  ['向く', 'volitional'],
  ['逃す', 'potential'],
  ['逃す', 'passive'],
  ['逃す', 'causative'],
  ['逃す', 'volitional'],
  ['広がる', 'potential'],
  ['広がる', 'passive'],
  ['広がる', 'causative'],
  ['広がる', 'volitional'],
  ['広がる', 'imperative'],
  ['深まる', 'potential'],
  ['深まる', 'passive'],
  ['深まる', 'causative'],
  ['深まる', 'volitional'],
  ['深まる', 'imperative'],
  ['回る', 'passive'],
  ['回る', 'causative'],
  ['目立つ', 'potential'],
  ['目立つ', 'passive'],
  ['目立つ', 'volitional'],
  ['目立つ', 'imperative'],
  ['申す', 'potential'],
  ['申す', 'passive'],
  ['申す', 'causative'],
  ['申す', 'volitional'],
  ['申す', 'imperative'],
  ['いただく', 'passive'],
  ['いただく', 'causative'],
  ['いただく', 'imperative'],
  ['ご覧になる', 'passive'],
  ['ご覧になる', 'causative'],
  ['ご覧になる', 'volitional'],
  ['ご覧になる', 'imperative'],
  ['召し上がる', 'potential'],
  ['召し上がる', 'passive'],
  ['召し上がる', 'causative'],
  ['召し上がる', 'volitional'],
  ['痛む', 'potential'],
  ['痛む', 'passive'],
  ['痛む', 'causative'],
  ['痛む', 'volitional'],
  ['痛む', 'imperative'],
  ['落ち着く', 'passive'],
  ['引き返す', 'passive'],
  ['引き返す', 'causative'],
  ['乗り換える', 'passive'],
  ['当てはまる', 'potential'],
  ['当てはまる', 'passive'],
  ['当てはまる', 'causative'],
  ['当てはまる', 'volitional'],
  ['当てはまる', 'imperative'],
  ['盛り上がる', 'potential'],
  ['盛り上がる', 'passive'],
  ['盛り上がる', 'causative'],
  ['盛り上がる', 'imperative'],
  ['飛び出す', 'passive'],
  ['飛び出す', 'causative'],
  ['騒がせる', 'potential'],
  ['騒がせる', 'passive'],
  ['騒がせる', 'causative'],
  ['突き当たる', 'potential'],
  ['突き当たる', 'passive'],
  ['突き当たる', 'causative'],
  ['突き当たる', 'volitional'],
  ['突き当たる', 'imperative'],
  ['食べ過ぎる', 'potential'],
  ['食べ過ぎる', 'passive'],
  ['食べ過ぎる', 'causative'],
  ['食べ過ぎる', 'volitional'],
  ['食べ過ぎる', 'imperative'],
  ['飲み過ぎる', 'potential'],
  ['飲み過ぎる', 'passive'],
  ['飲み過ぎる', 'causative'],
  ['飲み過ぎる', 'volitional'],
  ['飲み過ぎる', 'imperative'],
  ['立ち上がる', 'passive'],
  ['思い込む', 'potential'],
  ['思い込む', 'passive'],
  ['思い込む', 'volitional'],
  ['思い込む', 'imperative'],
  ['申し上げる', 'passive'],
  ['申し上げる', 'causative'],
  ['申し上げる', 'imperative'],
  ['おる', 'te'],
  ['おる', 'ta'],
  ['おる', 'nai'],
  ['おる', 'potential'],
  ['おる', 'passive'],
  ['おる', 'causative'],
  ['おる', 'conditional_ba'],
  ['おる', 'conditional_tara'],
  ['おる', 'volitional'],
  ['おる', 'imperative'],
  ['拝見する', 'passive'],
  ['拝見する', 'causative'],
  ['拝見する', 'imperative'],
  ['睨む', 'potential'],
  ['睨む', 'causative'],
  ['頷く', 'passive'],
  ['微笑む', 'potential'],
  ['微笑む', 'passive'],
  ['微笑む', 'causative'],
  ['微笑む', 'imperative'],
  ['膨らむ', 'potential'],
  ['膨らむ', 'passive'],
  ['膨らむ', 'causative'],
  ['膨らむ', 'volitional'],
  ['膨らむ', 'imperative'],
  ['縮む', 'potential'],
  ['縮む', 'passive'],
  ['縮む', 'causative'],
  ['縮む', 'volitional'],
  ['縮む', 'imperative'],
  ['膨らませる', 'causative'],
  ['閃く', 'potential'],
  ['閃く', 'passive'],
  ['閃く', 'causative'],
  ['閃く', 'volitional'],
  ['閃く', 'imperative'],
  ['惚れる', 'potential'],
  ['惚れる', 'passive'],
  ['惚れる', 'volitional'],
  ['惚れる', 'imperative'],
  ['甦る', 'potential'],
  ['甦る', 'passive'],
  ['甦る', 'volitional'],
  ['甦る', 'imperative'],
  ['弾む', 'potential'],
  ['弾む', 'passive'],
  ['弾む', 'volitional'],
  ['弾む', 'imperative'],
  ['売り切れる', 'potential'],
  ['売り切れる', 'passive'],
  ['売り切れる', 'causative'],
  ['売り切れる', 'volitional'],
  ['売り切れる', 'imperative'],
  ['入り込む', 'imperative'],
  ['行き詰まる', 'potential'],
  ['行き詰まる', 'passive'],
  ['行き詰まる', 'causative'],
  ['行き詰まる', 'volitional'],
  ['行き詰まる', 'imperative'],
  ['付き合う', 'passive'],
  ['枯れる', 'potential'],
  ['枯れる', 'passive'],
  ['枯れる', 'volitional'],
  ['枯れる', 'imperative'],
  ['腐る', 'potential'],
  ['腐る', 'passive'],
  ['腐る', 'volitional'],
  ['腐る', 'imperative'],
  ['凍る', 'potential'],
  ['凍る', 'passive'],
  ['凍る', 'volitional'],
  ['凍る', 'imperative'],
  ['溶ける', 'potential'],
  ['溶ける', 'passive'],
  ['溶ける', 'causative'],
  ['溶ける', 'volitional'],
  ['溶ける', 'imperative'],
  ['明ける', 'potential'],
  ['明ける', 'passive'],
  ['明ける', 'causative'],
  ['明ける', 'volitional'],
  ['明ける', 'imperative'],
  ['暮れる', 'potential'],
  ['暮れる', 'passive'],
  ['暮れる', 'causative'],
  ['暮れる', 'volitional'],
  ['暮れる', 'imperative'],
  ['居眠りする', 'potential'],
  ['居眠りする', 'passive'],
  ['居眠りする', 'volitional'],
  ['居眠りする', 'imperative'],
  ['油断する', 'potential'],
  ['油断する', 'passive'],
  ['油断する', 'volitional'],
  ['油断する', 'imperative'],
  ['辿り着く', 'passive'],
  ['辿り着く', 'causative'],
  ['差し掛かる', 'potential'],
  ['差し掛かる', 'passive'],
  ['差し掛かる', 'causative'],
  ['差し掛かる', 'volitional'],
  ['差し掛かる', 'imperative'],
  ['着替える', 'passive'],
  ['浮き上がる', 'potential'],
  ['浮き上がる', 'passive'],
  ['浮き上がる', 'causative'],
  ['浮き上がる', 'volitional'],
  ['浮き上がる', 'imperative'],
  ['発足する', 'passive'],
  ['発足する', 'volitional'],
  ['発足する', 'imperative'],
  ['対立する', 'potential'],
  ['対立する', 'passive'],
  ['対立する', 'volitional'],
  ['対立する', 'imperative'],
  ['協力する', 'passive'],
  ['競争する', 'passive'],
  ['参る', 'potential'],
  ['参る', 'passive'],
  ['参る', 'causative'],
  ['存じる', 'ta'],
  ['存じる', 'potential'],
  ['存じる', 'passive'],
  ['存じる', 'causative'],
  ['存じる', 'conditional_ba'],
  ['存じる', 'conditional_tara'],
  ['存じる', 'volitional'],
  ['存じる', 'imperative'],
  ['溢れ出す', 'potential'],
  ['溢れ出す', 'passive'],
  ['溢れ出す', 'causative'],
  ['溢れ出す', 'volitional'],
  ['溢れ出す', 'imperative'],
  ['切り抜ける', 'passive'],
  ['張り切る', 'potential'],
  ['張り切る', 'passive'],
  ['振り向く', 'potential'],
  ['打ち勝つ', 'passive'],
  ['立ち止まる', 'passive'],
  ['出会う', 'passive'],
  ['出会う', 'causative'],
  ['出会う', 'imperative'],
  ['噛み締める', 'passive'],
  ['起き上がる', 'passive'],
  ['締まる', 'potential'],
  ['締まる', 'passive'],
  ['締まる', 'causative'],
  ['締まる', 'volitional'],
  ['締まる', 'imperative'],
  ['緩む', 'potential'],
  ['緩む', 'passive'],
  ['緩む', 'causative'],
  ['緩む', 'volitional'],
  ['緩む', 'imperative'],
  ['栄える', 'potential'],
  ['栄える', 'passive'],
  ['栄える', 'causative'],
  ['栄える', 'volitional'],
  ['栄える', 'imperative'],
  ['錆びる', 'potential'],
  ['錆びる', 'passive'],
  ['錆びる', 'causative'],
  ['錆びる', 'volitional'],
  ['錆びる', 'imperative'],
  ['納得する', 'passive'],
  ['納得する', 'volitional'],
  ['納得する', 'imperative'],
  ['察する', 'potential'],
  ['察する', 'passive'],
  ['察する', 'causative'],
  ['察する', 'imperative'],
  ['適する', 'conditional_tara'],
  ['思い至る', 'potential'],
  ['思い至る', 'passive'],
  ['思い至る', 'causative'],
  ['思い至る', 'volitional'],
  ['思い至る', 'imperative'],
  ['立ち回る', 'passive'],
  ['立ち直る', 'passive'],
  ['立ちはだかる', 'potential'],
  ['立ちはだかる', 'passive'],
  ['立ちはだかる', 'causative'],
  ['立ちはだかる', 'volitional'],
  ['立ちはだかる', 'imperative'],
  ['擦れ違う', 'passive'],
  ['擦れ違う', 'causative'],
  ['擦れ違う', 'volitional'],
  ['擦れ違う', 'imperative'],
  ['言い争う', 'volitional'],
  ['言い争う', 'imperative'],
  ['入れ替わる', 'potential'],
  ['入れ替わる', 'passive'],
  ['入れ替わる', 'causative'],
  ['入れ替わる', 'volitional'],
  ['入れ替わる', 'imperative'],
  ['吹き出す', 'potential'],
  ['吹き出す', 'passive'],
  ['吹き出す', 'causative'],
  ['吹き出す', 'volitional'],
  ['吹き出す', 'imperative'],
  ['見出す', 'causative'],
  ['見出す', 'volitional'],
  ['見出す', 'imperative'],
  ['講演する', 'passive'],
  ['講演する', 'imperative'],
  ['合意する', 'passive'],
  ['合意する', 'imperative'],
  ['決裂する', 'potential'],
  ['決裂する', 'passive'],
  ['決裂する', 'causative'],
  ['決裂する', 'volitional'],
  ['決裂する', 'imperative'],
  ['妥結する', 'potential'],
  ['妥結する', 'passive'],
  ['妥結する', 'causative'],
  ['妥結する', 'volitional'],
  ['妥結する', 'imperative'],
  ['所有する', 'volitional'],
  ['所有する', 'imperative'],
  ['譲り合う', 'passive'],
  ['剥ける', 'potential'],
  ['剥ける', 'passive'],
  ['剥ける', 'causative'],
  ['剥ける', 'volitional'],
  ['剥ける', 'imperative'],
  ['すくむ', 'potential'],
  ['すくむ', 'passive'],
  ['すくむ', 'causative'],
  ['すくむ', 'volitional'],
  ['すくむ', 'imperative'],
  ['ずれる', 'potential'],
  ['ずれる', 'passive'],
  ['ずれる', 'causative'],
  ['ずれる', 'volitional'],
  ['ずれる', 'imperative'],
  ['はみ出す', 'potential'],
  ['はみ出す', 'passive'],
  ['はみ出す', 'causative'],
  ['はみ出す', 'volitional'],
  ['はみ出す', 'imperative'],
  ['のめり込む', 'potential'],
  ['のめり込む', 'passive'],
  ['のめり込む', 'causative'],
  ['のめり込む', 'imperative'],
  ['のさばる', 'potential'],
  ['のさばる', 'passive'],
  ['のさばる', 'causative'],
  ['のさばる', 'volitional'],
  ['のさばる', 'imperative'],
  ['ぼやく', 'potential'],
  ['ぼやく', 'passive'],
  ['ぼやく', 'causative'],
  ['ぼやく', 'conditional_ba'],
  ['ぼやく', 'imperative'],
  ['たかる', 'potential'],
  ['たかる', 'volitional'],
  ['たかる', 'imperative'],
  ['ぐずる', 'potential'],
  ['ぐずる', 'passive'],
  ['ぐずる', 'causative'],
  ['ぐずる', 'volitional'],
  ['ぐずる', 'imperative'],
  ['すがる', 'passive'],
  ['すがる', 'imperative'],
  ['まごつく', 'potential'],
  ['まごつく', 'passive'],
  ['まごつく', 'causative'],
  ['まごつく', 'volitional'],
  ['まごつく', 'imperative'],
  ['たじろぐ', 'potential'],
  ['たじろぐ', 'passive'],
  ['たじろぐ', 'causative'],
  ['たじろぐ', 'volitional'],
  ['たじろぐ', 'imperative'],
  ['うろつく', 'volitional'],
  ['うろつく', 'imperative'],
  ['志す', 'passive'],
  ['志す', 'causative'],
  ['見届ける', 'passive'],
  ['分かち合う', 'passive'],
  ['語り合う', 'passive'],
  ['語り合う', 'imperative'],
  ['認め合う', 'passive'],
  ['認め合う', 'imperative'],
  ['補い合う', 'passive'],
  ['補い合う', 'imperative'],
  ['高め合う', 'passive'],
  ['競い合う', 'passive'],
  ['支持する', 'imperative'],
  ['物足りる', 'masu'],
  ['物足りる', 'te'],
  ['物足りる', 'ta'],
  ['物足りる', 'potential'],
  ['物足りる', 'passive'],
  ['物足りる', 'causative'],
  ['物足りる', 'conditional_ba'],
  ['物足りる', 'conditional_tara'],
  ['物足りる', 'volitional'],
  ['物足りる', 'imperative'],
  ['恥じる', 'potential'],
  ['恥じる', 'passive'],
  ['恥じる', 'imperative'],
  ['恥じらう', 'potential'],
  ['恥じらう', 'passive'],
  ['恥じらう', 'causative'],
  ['恥じらう', 'conditional_ba'],
  ['恥じらう', 'volitional'],
  ['恥じらう', 'imperative'],
  ['損なう', 'potential'],
  ['損なう', 'causative'],
  ['損なう', 'imperative'],
  ['損ねる', 'potential'],
  ['損ねる', 'passive'],
  ['損ねる', 'causative'],
  ['損ねる', 'volitional'],
  ['損ねる', 'imperative'],
  ['余る', 'potential'],
  ['余る', 'passive'],
  ['余る', 'volitional'],
  ['余る', 'imperative'],
];

describe('N3 form example sentences', () => {
  const entries: [string, ConjugationForm, string][] = [];
  for (const [verb, forms] of Object.entries(n3dataset)) {
    for (const [form, sentence] of Object.entries(forms)) {
      entries.push([verb, form as ConjugationForm, sentence as string]);
    }
  }

  it('covers a non-trivial number of sentences', () => {
    expect(entries.length).toBeGreaterThan(3000);
  });

  it('matches the expected count by form', () => {
    const counts: Partial<Record<ConjugationForm, number>> = {};
    for (const [, form] of entries) {
      counts[form] = (counts[form] || 0) + 1;
    }
    expect(counts).toEqual(n3ExpectedCountsByForm);
  });

  it('only references N3 verbs that exist', () => {
    for (const verb of Object.keys(n3dataset)) {
      expect(verbs[verb]).toBeDefined();
      expect(verbs[verb].jlpt).toBe('N3');
    }
  });

  it('each sentence contains its exact conjugated form (kanji or kana)', () => {
    const offenders: string[] = [];
    for (const [verb, form, sentence] of entries) {
      const data = verbs[verb];
      const kanji = conjugate(verb, data, form).value;
      const kana = conjugateReading(data, form);
      if (!sentence.includes(kanji) && !sentence.includes(kana)) {
        offenders.push(`${verb}:${form} -> "${sentence}" (expected ${kanji}/${kana})`);
      }
    }
    expect(offenders).toEqual([]);
  });

  it('generates no examples for N3 excludeForms forms', () => {
    expectExcludedFormsAbsent('N3', n3dataset);
  });

  it('omits only intentional non-exclude N3 forms', () => {
    expect(nonExcludeOmissions('N3', n3dataset)).toEqual(n3IntentionalOmissions);
  });
});

const n2dataset = n2 as Record<string, Partial<Record<ConjugationForm, string>>>;
const n2ExpectedCountsByForm: Partial<Record<ConjugationForm, number>> = {
  masu: 478,
  te: 478,
  ta: 478,
  nai: 478,
  potential: 322,
  passive: 313,
  causative: 356,
  conditional_ba: 475,
  conditional_tara: 478,
  volitional: 334,
  imperative: 314,
};

const n2IntentionalOmissions: [string, ConjugationForm][] = [
  ['退く', 'potential'],
  ['退く', 'passive'],
  ['退く', 'causative'],
  ['退く', 'imperative'],
  ['悟る', 'causative'],
  ['悟る', 'volitional'],
  ['悟る', 'imperative'],
  ['恐れる', 'potential'],
  ['恐れる', 'volitional'],
  ['恐れる', 'imperative'],
  ['憎む', 'volitional'],
  ['憎む', 'imperative'],
  ['惹かれる', 'potential'],
  ['惹かれる', 'passive'],
  ['惹かれる', 'causative'],
  ['惹かれる', 'volitional'],
  ['惹かれる', 'imperative'],
  ['悩む', 'potential'],
  ['悩む', 'passive'],
  ['悩む', 'volitional'],
  ['悩む', 'imperative'],
  ['耐える', 'passive'],
  ['溢れる', 'potential'],
  ['溢れる', 'passive'],
  ['溢れる', 'causative'],
  ['溢れる', 'volitional'],
  ['溢れる', 'imperative'],
  ['率いる', 'potential'],
  ['漏れる', 'potential'],
  ['漏れる', 'passive'],
  ['漏れる', 'causative'],
  ['漏れる', 'volitional'],
  ['漏れる', 'imperative'],
  ['滑る', 'passive'],
  ['転ぶ', 'potential'],
  ['転ぶ', 'passive'],
  ['転ぶ', 'volitional'],
  ['転ぶ', 'imperative'],
  ['発展する', 'potential'],
  ['発展する', 'passive'],
  ['発展する', 'volitional'],
  ['発展する', 'imperative'],
  ['実現する', 'imperative'],
  ['貢献する', 'passive'],
  ['貢献する', 'imperative'],
  ['生じる', 'potential'],
  ['生じる', 'passive'],
  ['生じる', 'volitional'],
  ['生じる', 'imperative'],
  ['応じる', 'potential'],
  ['応じる', 'passive'],
  ['応じる', 'imperative'],
  ['通じる', 'potential'],
  ['通じる', 'passive'],
  ['通じる', 'causative'],
  ['通じる', 'volitional'],
  ['通じる', 'imperative'],
  ['感じる', 'passive'],
  ['感じる', 'imperative'],
  ['論じる', 'potential'],
  ['禁じる', 'potential'],
  ['禁じる', 'imperative'],
  ['命じる', 'potential'],
  ['命じる', 'volitional'],
  ['命じる', 'imperative'],
  ['報じる', 'potential'],
  ['報じる', 'causative'],
  ['報じる', 'volitional'],
  ['報じる', 'imperative'],
  ['称える', 'potential'],
  ['捧げる', 'potential'],
  ['省みる', 'potential'],
  ['省みる', 'passive'],
  ['省みる', 'causative'],
  ['漂う', 'potential'],
  ['漂う', 'passive'],
  ['漂う', 'volitional'],
  ['漂う', 'imperative'],
  ['競う', 'passive'],
  ['整う', 'potential'],
  ['整う', 'passive'],
  ['整う', 'causative'],
  ['整う', 'volitional'],
  ['整う', 'imperative'],
  ['潤す', 'causative'],
  ['潤す', 'imperative'],
  ['恵まれる', 'potential'],
  ['恵まれる', 'passive'],
  ['恵まれる', 'causative'],
  ['恵まれる', 'volitional'],
  ['恵まれる', 'imperative'],
  ['恵む', 'potential'],
  ['恵む', 'passive'],
  ['恵む', 'causative'],
  ['恵む', 'volitional'],
  ['恵む', 'imperative'],
  ['催す', 'imperative'],
  ['震わせる', 'potential'],
  ['震わせる', 'passive'],
  ['震わせる', 'causative'],
  ['背く', 'potential'],
  ['背く', 'passive'],
  ['裂く', 'potential'],
  ['嫌う', 'potential'],
  ['嫌う', 'causative'],
  ['嫌う', 'volitional'],
  ['嫌う', 'imperative'],
  ['懐かしむ', 'potential'],
  ['懐かしむ', 'passive'],
  ['懐かしむ', 'causative'],
  ['懐かしむ', 'volitional'],
  ['懐かしむ', 'imperative'],
  ['発生する', 'potential'],
  ['発生する', 'passive'],
  ['発生する', 'volitional'],
  ['発生する', 'imperative'],
  ['回復する', 'passive'],
  ['回復する', 'volitional'],
  ['回復する', 'imperative'],
  ['傾く', 'potential'],
  ['傾く', 'passive'],
  ['傾く', 'causative'],
  ['傾く', 'volitional'],
  ['傾く', 'imperative'],
  ['浸る', 'potential'],
  ['浸る', 'passive'],
  ['浸る', 'causative'],
  ['浸る', 'imperative'],
  ['偏る', 'potential'],
  ['偏る', 'passive'],
  ['偏る', 'causative'],
  ['偏る', 'volitional'],
  ['偏る', 'imperative'],
  ['遡る', 'passive'],
  ['遡る', 'causative'],
  ['遡る', 'volitional'],
  ['遡る', 'imperative'],
  ['挫く', 'potential'],
  ['潜る', 'passive'],
  ['飢える', 'potential'],
  ['飢える', 'passive'],
  ['飢える', 'volitional'],
  ['飢える', 'imperative'],
  ['赴く', 'potential'],
  ['赴く', 'passive'],
  ['赴く', 'causative'],
  ['兼ねる', 'potential'],
  ['兼ねる', 'passive'],
  ['兼ねる', 'causative'],
  ['兼ねる', 'volitional'],
  ['兼ねる', 'imperative'],
  ['絡む', 'potential'],
  ['絡む', 'volitional'],
  ['絡む', 'imperative'],
  ['凝る', 'potential'],
  ['凝る', 'passive'],
  ['凝る', 'causative'],
  ['凝る', 'volitional'],
  ['凝る', 'imperative'],
  ['共感する', 'passive'],
  ['共感する', 'causative'],
  ['共感する', 'volitional'],
  ['共感する', 'imperative'],
  ['配慮する', 'imperative'],
  ['反映する', 'imperative'],
  ['満たす', 'causative'],
  ['滞る', 'potential'],
  ['滞る', 'passive'],
  ['滞る', 'causative'],
  ['滞る', 'volitional'],
  ['滞る', 'imperative'],
  ['妨げる', 'causative'],
  ['妨げる', 'volitional'],
  ['妨げる', 'imperative'],
  ['慕う', 'volitional'],
  ['慕う', 'imperative'],
  ['甘える', 'passive'],
  ['甘える', 'volitional'],
  ['焦る', 'potential'],
  ['焦る', 'passive'],
  ['焦る', 'volitional'],
  ['焦る', 'imperative'],
  ['呆れる', 'potential'],
  ['呆れる', 'volitional'],
  ['呆れる', 'imperative'],
  ['飽きる', 'potential'],
  ['飽きる', 'volitional'],
  ['飽きる', 'imperative'],
  ['憧れる', 'potential'],
  ['憧れる', 'causative'],
  ['憧れる', 'volitional'],
  ['憧れる', 'imperative'],
  ['戸惑う', 'potential'],
  ['戸惑う', 'passive'],
  ['戸惑う', 'volitional'],
  ['戸惑う', 'imperative'],
  ['見込む', 'causative'],
  ['見通す', 'causative'],
  ['踏まえる', 'potential'],
  ['踏まえる', 'causative'],
  ['裏付ける', 'volitional'],
  ['裏付ける', 'imperative'],
  ['追い付く', 'passive'],
  ['追い付く', 'causative'],
  ['染み込む', 'potential'],
  ['染み込む', 'passive'],
  ['染み込む', 'causative'],
  ['染み込む', 'volitional'],
  ['染み込む', 'imperative'],
  ['儲かる', 'potential'],
  ['儲かる', 'passive'],
  ['儲かる', 'causative'],
  ['儲かる', 'volitional'],
  ['儲かる', 'imperative'],
  ['妬む', 'imperative'],
  ['嫉む', 'potential'],
  ['嫉む', 'causative'],
  ['嫉む', 'volitional'],
  ['嫉む', 'imperative'],
  ['潰れる', 'potential'],
  ['潰れる', 'passive'],
  ['潰れる', 'causative'],
  ['潰れる', 'volitional'],
  ['潰れる', 'imperative'],
  ['崩れる', 'potential'],
  ['崩れる', 'passive'],
  ['崩れる', 'causative'],
  ['崩れる', 'volitional'],
  ['崩れる', 'imperative'],
  ['腫れる', 'potential'],
  ['腫れる', 'passive'],
  ['腫れる', 'causative'],
  ['腫れる', 'volitional'],
  ['腫れる', 'imperative'],
  ['痺れる', 'potential'],
  ['痺れる', 'passive'],
  ['痺れる', 'causative'],
  ['痺れる', 'volitional'],
  ['痺れる', 'imperative'],
  ['怯える', 'potential'],
  ['怯える', 'passive'],
  ['怯える', 'volitional'],
  ['怯える', 'imperative'],
  ['和らぐ', 'potential'],
  ['和らぐ', 'passive'],
  ['和らぐ', 'causative'],
  ['和らぐ', 'volitional'],
  ['和らぐ', 'imperative'],
  ['和らげる', 'passive'],
  ['揃う', 'potential'],
  ['揃う', 'passive'],
  ['揃う', 'causative'],
  ['揃う', 'volitional'],
  ['揃う', 'imperative'],
  ['揃える', 'passive'],
  ['滲む', 'potential'],
  ['滲む', 'passive'],
  ['滲む', 'causative'],
  ['滲む', 'volitional'],
  ['滲む', 'imperative'],
  ['剥がれる', 'potential'],
  ['剥がれる', 'passive'],
  ['剥がれる', 'causative'],
  ['剥がれる', 'volitional'],
  ['剥がれる', 'imperative'],
  ['噛み合う', 'potential'],
  ['噛み合う', 'passive'],
  ['噛み合う', 'volitional'],
  ['噛み合う', 'imperative'],
  ['立ち入る', 'passive'],
  ['申し立てる', 'passive'],
  ['潜む', 'potential'],
  ['潜む', 'passive'],
  ['潜む', 'volitional'],
  ['潜む', 'imperative'],
  ['励ます', 'causative'],
  ['励む', 'passive'],
  ['励む', 'causative'],
  ['煩う', 'potential'],
  ['煩う', 'passive'],
  ['煩う', 'conditional_ba'],
  ['煩う', 'volitional'],
  ['煩う', 'imperative'],
  ['煩わす', 'potential'],
  ['煩わす', 'passive'],
  ['煩わす', 'causative'],
  ['煩わす', 'imperative'],
  ['蘇る', 'potential'],
  ['蘇る', 'passive'],
  ['蘇る', 'volitional'],
  ['蘇る', 'imperative'],
  ['堪える', 'passive'],
  ['彷徨う', 'potential'],
  ['彷徨う', 'passive'],
  ['彷徨う', 'volitional'],
  ['彷徨う', 'imperative'],
  ['逸れる', 'potential'],
  ['逸れる', 'passive'],
  ['逸れる', 'causative'],
  ['逸れる', 'volitional'],
  ['逸れる', 'imperative'],
  ['紛れ込む', 'potential'],
  ['紛れ込む', 'passive'],
  ['紛れ込む', 'volitional'],
  ['紛れ込む', 'imperative'],
  ['寄り添う', 'potential'],
  ['寄り添う', 'passive'],
  ['寄り添う', 'causative'],
  ['寄り添う', 'volitional'],
  ['寄り添う', 'imperative'],
  ['食い違う', 'potential'],
  ['食い違う', 'passive'],
  ['食い違う', 'causative'],
  ['食い違う', 'volitional'],
  ['食い違う', 'imperative'],
  ['消耗する', 'potential'],
  ['消耗する', 'volitional'],
  ['消耗する', 'imperative'],
  ['干渉する', 'potential'],
  ['干渉する', 'volitional'],
  ['干渉する', 'imperative'],
  ['妥協する', 'passive'],
  ['妥協する', 'imperative'],
  ['矛盾する', 'potential'],
  ['矛盾する', 'passive'],
  ['矛盾する', 'causative'],
  ['矛盾する', 'volitional'],
  ['矛盾する', 'imperative'],
  ['拗ねる', 'potential'],
  ['拗ねる', 'passive'],
  ['拗ねる', 'imperative'],
  ['萎える', 'potential'],
  ['萎える', 'passive'],
  ['萎える', 'volitional'],
  ['萎える', 'imperative'],
  ['怯む', 'potential'],
  ['怯む', 'passive'],
  ['怯む', 'volitional'],
  ['怯む', 'imperative'],
  ['窮まる', 'potential'],
  ['窮まる', 'passive'],
  ['窮まる', 'causative'],
  ['窮まる', 'volitional'],
  ['窮まる', 'imperative'],
  ['儚む', 'potential'],
  ['儚む', 'passive'],
  ['儚む', 'causative'],
  ['儚む', 'volitional'],
  ['儚む', 'imperative'],
  ['蓋する', 'passive'],
  ['定着する', 'potential'],
  ['定着する', 'passive'],
  ['定着する', 'causative'],
  ['定着する', 'volitional'],
  ['定着する', 'imperative'],
  ['懸念する', 'potential'],
  ['懸念する', 'causative'],
  ['懸念する', 'volitional'],
  ['懸念する', 'imperative'],
  ['覆い隠す', 'causative'],
  ['持て余す', 'volitional'],
  ['持て余す', 'imperative'],
  ['唆す', 'volitional'],
  ['唆す', 'imperative'],
  ['宿る', 'potential'],
  ['宿る', 'passive'],
  ['宿る', 'volitional'],
  ['宿る', 'imperative'],
  ['授かる', 'potential'],
  ['授かる', 'passive'],
  ['授かる', 'causative'],
  ['授かる', 'volitional'],
  ['授かる', 'imperative'],
  ['授ける', 'imperative'],
  ['浸食する', 'potential'],
  ['浸食する', 'causative'],
  ['浸食する', 'volitional'],
  ['浸食する', 'imperative'],
  ['衰える', 'potential'],
  ['衰える', 'passive'],
  ['衰える', 'volitional'],
  ['衰える', 'imperative'],
  ['抱く', 'potential'],
  ['突き進む', 'passive'],
  ['差し迫る', 'potential'],
  ['差し迫る', 'passive'],
  ['差し迫る', 'causative'],
  ['差し迫る', 'volitional'],
  ['差し迫る', 'imperative'],
  ['行き届く', 'potential'],
  ['行き届く', 'passive'],
  ['行き届く', 'causative'],
  ['行き届く', 'volitional'],
  ['行き届く', 'imperative'],
  ['飛び交う', 'potential'],
  ['飛び交う', 'passive'],
  ['飛び交う', 'causative'],
  ['飛び交う', 'volitional'],
  ['飛び交う', 'imperative'],
  ['染み付く', 'potential'],
  ['染み付く', 'passive'],
  ['染み付く', 'causative'],
  ['染み付く', 'volitional'],
  ['染み付く', 'imperative'],
  ['根差す', 'potential'],
  ['根差す', 'passive'],
  ['根差す', 'causative'],
  ['根差す', 'volitional'],
  ['根差す', 'imperative'],
  ['拗れる', 'potential'],
  ['拗れる', 'passive'],
  ['拗れる', 'causative'],
  ['拗れる', 'volitional'],
  ['拗れる', 'imperative'],
  ['蝕む', 'potential'],
  ['蝕む', 'causative'],
  ['蝕む', 'volitional'],
  ['蝕む', 'imperative'],
  ['揉める', 'potential'],
  ['揉める', 'passive'],
  ['揉める', 'causative'],
  ['揉める', 'volitional'],
  ['揉める', 'imperative'],
  ['嵌まる', 'potential'],
  ['嵌まる', 'passive'],
  ['嵌まる', 'causative'],
  ['嵌まる', 'volitional'],
  ['嵌まる', 'imperative'],
  ['嵌める', 'potential'],
  ['拠る', 'potential'],
  ['拠る', 'passive'],
  ['拠る', 'causative'],
  ['拠る', 'volitional'],
  ['拠る', 'imperative'],
  ['ときめく', 'potential'],
  ['ときめく', 'passive'],
  ['ときめく', 'volitional'],
  ['ときめく', 'imperative'],
  ['見惚れる', 'potential'],
  ['見惚れる', 'passive'],
  ['見惚れる', 'volitional'],
  ['見惚れる', 'imperative'],
  ['聞き入る', 'potential'],
  ['聞き入る', 'passive'],
  ['聞き入る', 'causative'],
  ['聞き入る', 'imperative'],
  ['酔う', 'potential'],
  ['酔う', 'volitional'],
  ['酔う', 'imperative'],
  ['酔わせる', 'potential'],
  ['酔わせる', 'causative'],
  ['囃し立てる', 'potential'],
  ['絡み合う', 'potential'],
  ['絡み合う', 'passive'],
  ['絡み合う', 'volitional'],
  ['絡み合う', 'imperative'],
  ['食い下がる', 'passive'],
  ['食い下がる', 'causative'],
  ['食い込む', 'potential'],
  ['食い込む', 'passive'],
  ['食い込む', 'causative'],
  ['食い込む', 'volitional'],
  ['食い込む', 'imperative'],
  ['振り絞る', 'passive'],
  ['落ち込む', 'potential'],
  ['落ち込む', 'passive'],
  ['落ち込む', 'causative'],
  ['落ち込む', 'volitional'],
  ['落ち込む', 'imperative'],
  ['落ち着ける', 'passive'],
  ['打ち負かす', 'causative'],
  ['言い分ける', 'passive'],
  ['言い分ける', 'causative'],
  ['言い分ける', 'volitional'],
  ['言い分ける', 'imperative'],
  ['拘る', 'potential'],
  ['拘る', 'passive'],
  ['拘る', 'causative'],
  ['拘る', 'imperative'],
  ['捗る', 'potential'],
  ['捗る', 'passive'],
  ['捗る', 'causative'],
  ['捗る', 'volitional'],
  ['捗る', 'imperative'],
  ['赴任する', 'passive'],
  ['着任する', 'passive'],
  ['辞任する', 'passive'],
  ['就任する', 'passive'],
  ['思い留まる', 'potential'],
  ['思い留まる', 'passive'],
  ['思い留まる', 'volitional'],
  ['差し控える', 'potential'],
  ['差し控える', 'passive'],
  ['差し控える', 'volitional'],
  ['差し控える', 'imperative'],
  ['持ち堪える', 'potential'],
  ['持ち堪える', 'passive'],
  ['持ち堪える', 'causative'],
  ['持ち堪える', 'volitional'],
  ['持ち堪える', 'imperative'],
  ['長引く', 'potential'],
  ['長引く', 'passive'],
  ['長引く', 'causative'],
  ['長引く', 'volitional'],
  ['長引く', 'imperative'],
  ['早まる', 'potential'],
  ['早まる', 'passive'],
  ['早まる', 'causative'],
  ['早まる', 'volitional'],
  ['早まる', 'imperative'],
  ['遅らせる', 'passive'],
  ['遅らせる', 'causative'],
  ['高まる', 'potential'],
  ['高まる', 'passive'],
  ['高まる', 'causative'],
  ['高まる', 'volitional'],
  ['高まる', 'imperative'],
  ['高める', 'potential'],
  ['弱まる', 'potential'],
  ['弱まる', 'passive'],
  ['弱まる', 'causative'],
  ['弱まる', 'volitional'],
  ['弱まる', 'imperative'],
  ['弱める', 'potential'],
  ['強まる', 'potential'],
  ['強まる', 'passive'],
  ['強まる', 'causative'],
  ['強まる', 'volitional'],
  ['強まる', 'imperative'],
  ['強める', 'potential'],
  ['狭まる', 'potential'],
  ['狭まる', 'passive'],
  ['狭まる', 'causative'],
  ['狭まる', 'volitional'],
  ['狭まる', 'imperative'],
  ['広まる', 'potential'],
  ['広まる', 'passive'],
  ['広まる', 'causative'],
  ['広まる', 'volitional'],
  ['広まる', 'imperative'],
  ['和解する', 'passive'],
  ['和解する', 'causative'],
  ['控訴する', 'passive'],
  ['控訴する', 'causative'],
  ['控訴する', 'imperative'],
  ['嘆く', 'volitional'],
  ['暴れる', 'potential'],
  ['暴れる', 'passive'],
  ['弾ける', 'potential'],
  ['弾ける', 'passive'],
  ['弾ける', 'causative'],
  ['弾ける', 'volitional'],
  ['弾ける', 'imperative'],
  ['怠ける', 'passive'],
  ['覆い被さる', 'potential'],
  ['覆い被さる', 'passive'],
  ['覆い被さる', 'causative'],
  ['覆い被さる', 'conditional_ba'],
  ['覆い被さる', 'imperative'],
  ['噛み付く', 'potential'],
  ['噛み付く', 'volitional'],
  ['噛み付く', 'imperative'],
  ['とぼける', 'passive'],
  ['とぼける', 'causative'],
  ['ほくそ笑む', 'potential'],
  ['ほくそ笑む', 'passive'],
  ['ほくそ笑む', 'causative'],
  ['ほくそ笑む', 'volitional'],
  ['ほくそ笑む', 'imperative'],
  ['でしゃばる', 'passive'],
  ['でしゃばる', 'causative'],
  ['でしゃばる', 'imperative'],
  ['しくじる', 'potential'],
  ['しくじる', 'passive'],
  ['しくじる', 'causative'],
  ['しくじる', 'volitional'],
  ['しくじる', 'imperative'],
  ['立て籠もる', 'potential'],
  ['立て籠もる', 'passive'],
  ['立て籠もる', 'causative'],
  ['飛び掛かる', 'potential'],
  ['突っ張る', 'potential'],
  ['突っ張る', 'passive'],
  ['突っ張る', 'causative'],
  ['突っ張る', 'volitional'],
  ['突っ張る', 'imperative'],
  ['突っ走る', 'potential'],
  ['突っ走る', 'passive'],
  ['踏ん張る', 'passive'],
  ['踏ん張る', 'causative'],
  ['見切り発車する', 'potential'],
  ['見切り発車する', 'passive'],
  ['見切り発車する', 'imperative'],
  ['逆上する', 'potential'],
  ['逆上する', 'passive'],
  ['逆上する', 'volitional'],
  ['逆上する', 'imperative'],
  ['激昂する', 'potential'],
  ['激昂する', 'passive'],
  ['激昂する', 'volitional'],
  ['激昂する', 'imperative'],
  ['辟易する', 'potential'],
  ['辟易する', 'passive'],
  ['辟易する', 'volitional'],
  ['辟易する', 'imperative'],
  ['困惑する', 'potential'],
  ['困惑する', 'passive'],
  ['困惑する', 'volitional'],
  ['困惑する', 'imperative'],
  ['動揺する', 'potential'],
  ['動揺する', 'passive'],
  ['動揺する', 'volitional'],
  ['動揺する', 'imperative'],
  ['狼狽する', 'potential'],
  ['狼狽する', 'passive'],
  ['狼狽する', 'volitional'],
  ['狼狽する', 'imperative'],
  ['憤る', 'potential'],
  ['憤る', 'passive'],
  ['憤る', 'causative'],
  ['憤る', 'volitional'],
  ['憤る', 'imperative'],
  ['嫉妬する', 'potential'],
  ['嫉妬する', 'volitional'],
  ['嫉妬する', 'imperative'],
  ['懐疑する', 'causative'],
  ['懐疑する', 'volitional'],
  ['懐疑する', 'imperative'],
  ['喝采する', 'potential'],
  ['喝采する', 'passive'],
  ['喝采する', 'causative'],
  ['喝采する', 'volitional'],
  ['喝采する', 'imperative'],
  ['恐縮する', 'potential'],
  ['恐縮する', 'passive'],
  ['恐縮する', 'causative'],
  ['恐縮する', 'conditional_ba'],
  ['恐縮する', 'volitional'],
  ['恐縮する', 'imperative'],
  ['免れる', 'potential'],
  ['免れる', 'passive'],
  ['免れる', 'causative'],
  ['免れる', 'volitional'],
  ['免れる', 'imperative'],
  ['侵す', 'volitional'],
  ['侵す', 'imperative'],
  ['犯す', 'causative'],
  ['犯す', 'volitional'],
  ['犯す', 'imperative'],
  ['冒す', 'passive'],
  ['冒す', 'causative'],
  ['立ち退く', 'potential'],
  ['飛びつく', 'passive'],
  ['乗り切る', 'passive'],
  ['乗り出す', 'passive'],
  ['燃え上がる', 'potential'],
  ['燃え上がる', 'passive'],
  ['燃え上がる', 'causative'],
  ['燃え上がる', 'volitional'],
  ['燃え上がる', 'imperative'],
  ['燃え尽きる', 'potential'],
  ['燃え尽きる', 'passive'],
  ['燃え尽きる', 'causative'],
  ['燃え尽きる', 'volitional'],
  ['燃え尽きる', 'imperative'],
  ['流れ込む', 'potential'],
  ['流れ込む', 'passive'],
  ['流れ込む', 'causative'],
  ['流れ込む', 'volitional'],
  ['流れ込む', 'imperative'],
  ['成り済ます', 'passive'],
  ['成り済ます', 'causative'],
  ['成り済ます', 'imperative'],
  ['浮上する', 'passive'],
  ['沈没する', 'potential'],
  ['沈没する', 'passive'],
  ['沈没する', 'volitional'],
  ['沈没する', 'imperative'],
  ['噴火する', 'potential'],
  ['噴火する', 'passive'],
  ['噴火する', 'causative'],
  ['噴火する', 'volitional'],
  ['噴火する', 'imperative'],
  ['氾濫する', 'potential'],
  ['氾濫する', 'passive'],
  ['氾濫する', 'causative'],
  ['氾濫する', 'volitional'],
  ['氾濫する', 'imperative'],
  ['崩壊する', 'potential'],
  ['崩壊する', 'passive'],
  ['崩壊する', 'causative'],
  ['崩壊する', 'volitional'],
  ['崩壊する', 'imperative'],
  ['倒産する', 'potential'],
  ['倒産する', 'passive'],
  ['倒産する', 'causative'],
  ['倒産する', 'volitional'],
  ['倒産する', 'imperative'],
  ['暴落する', 'potential'],
  ['暴落する', 'passive'],
  ['暴落する', 'causative'],
  ['暴落する', 'volitional'],
  ['暴落する', 'imperative'],
  ['高騰する', 'potential'],
  ['高騰する', 'passive'],
  ['高騰する', 'causative'],
  ['高騰する', 'volitional'],
  ['高騰する', 'imperative'],
  ['横領する', 'volitional'],
  ['横領する', 'imperative'],
  ['収賄する', 'potential'],
  ['収賄する', 'passive'],
  ['収賄する', 'causative'],
  ['収賄する', 'volitional'],
  ['収賄する', 'imperative'],
  ['贈賄する', 'potential'],
  ['贈賄する', 'passive'],
  ['贈賄する', 'causative'],
  ['贈賄する', 'volitional'],
  ['贈賄する', 'imperative'],
  ['脱税する', 'potential'],
  ['脱税する', 'passive'],
  ['脱税する', 'causative'],
  ['脱税する', 'volitional'],
  ['脱税する', 'imperative'],
  ['押し寄せる', 'potential'],
  ['押し寄せる', 'passive'],
  ['押し寄せる', 'causative'],
  ['押し寄せる', 'volitional'],
  ['押し寄せる', 'imperative'],
  ['呼び寄せる', 'causative'],
  ['見合う', 'potential'],
  ['見合う', 'passive'],
  ['見合う', 'causative'],
  ['見合う', 'volitional'],
  ['見合う', 'imperative'],
  ['突き抜ける', 'passive'],
  ['突き抜ける', 'causative'],
  ['突き抜ける', 'volitional'],
  ['突き抜ける', 'imperative'],
  ['繰り延べる', 'causative'],
  ['繰り延べる', 'volitional'],
  ['繰り延べる', 'imperative'],
  ['繰り入れる', 'causative'],
  ['繰り入れる', 'volitional'],
  ['繰り入れる', 'imperative'],
  ['申し渡す', 'causative'],
  ['申し渡す', 'volitional'],
  ['申し渡す', 'imperative'],
  ['取り沙汰する', 'volitional'],
  ['立ち会う', 'passive'],
  ['打ち解ける', 'potential'],
  ['打ち解ける', 'passive'],
  ['打ち解ける', 'imperative'],
];

describe('N2 form example sentences', () => {
  const entries: [string, ConjugationForm, string][] = [];
  for (const [verb, forms] of Object.entries(n2dataset)) {
    for (const [form, sentence] of Object.entries(forms)) {
      entries.push([verb, form as ConjugationForm, sentence as string]);
    }
  }

  it('covers a non-trivial number of sentences', () => {
    expect(entries.length).toBeGreaterThan(4000);
  });

  it('matches the expected count by form', () => {
    const counts: Partial<Record<ConjugationForm, number>> = {};
    for (const [, form] of entries) {
      counts[form] = (counts[form] || 0) + 1;
    }
    expect(counts).toEqual(n2ExpectedCountsByForm);
  });

  it('only references N2 verbs that exist', () => {
    for (const verb of Object.keys(n2dataset)) {
      expect(verbs[verb]).toBeDefined();
      expect(verbs[verb].jlpt).toBe('N2');
    }
  });

  it('matches the N2 verb key set except intentionally absent 成り行く', () => {
    const expectedN2VerbKeys = Object.keys(verbs).filter(
      (verb) => verbs[verb].jlpt === 'N2' && verb !== '成り行く',
    );
    expect(Object.keys(n2dataset)).toEqual(expectedN2VerbKeys);
  });

  it('each sentence contains its exact conjugated form (kanji or kana)', () => {
    const offenders: string[] = [];
    for (const [verb, form, sentence] of entries) {
      const data = verbs[verb];
      const kanji = conjugate(verb, data, form).value;
      const kana = conjugateReading(data, form);
      if (!sentence.includes(kanji) && !sentence.includes(kana)) {
        offenders.push(`${verb}:${form} -> "${sentence}" (expected ${kanji}/${kana})`);
      }
    }
    expect(offenders).toEqual([]);
  });

  it('generates no examples for N2 excludeForms forms', () => {
    expectExcludedFormsAbsent('N2', n2dataset);
  });

  it('omits only intentional non-exclude N2 forms', () => {
    expect(nonExcludeOmissions('N2', n2dataset)).toEqual(n2IntentionalOmissions);
  });
});
