import { conjugate, conjugateReading, ConjugationForm, VerbData } from '../utils/conjugate';
import { getExampleSentence } from '../utils/formExamples';
import n5 from '../data/formExamples.n5.json';
import n4 from '../data/formExamples.n4.json';
import n3 from '../data/formExamples.n3.json';
import n1 from '../data/formExamples.n1.json';
import verbsJson from '../data/verbs.json';

const verbs = verbsJson as Record<string, VerbData>;
const dataset = n5 as Record<string, Partial<Record<ConjugationForm, string>>>;
const exampleForms: ConjugationForm[] = [
  'masu',
  'te',
  'ta',
  'nai',
  'potential',
  'passive',
  'causative',
  'conditional_ba',
  'conditional_tara',
  'volitional',
  'imperative',
];

function expectExcludedFormsAbsent(
  level: VerbData['jlpt'],
  examples: Record<string, Partial<Record<ConjugationForm, string>>>,
) {
  for (const [verb, data] of Object.entries(verbs)) {
    if (data.jlpt !== level) continue;
    for (const form of data.excludeForms || []) {
      expect(examples[verb]?.[form]).toBeUndefined();
      expect(getExampleSentence(verb, form)).toBeUndefined();
    }
  }
}

function nonExcludeOmissions(
  level: VerbData['jlpt'],
  examples: Record<string, Partial<Record<ConjugationForm, string>>>,
): [string, ConjugationForm][] {
  const omissions: [string, ConjugationForm][] = [];
  for (const verb of Object.keys(examples)) {
    const data = verbs[verb];
    if (!data || data.jlpt !== level) continue;
    const excluded = new Set(data.excludeForms || []);
    for (const form of exampleForms) {
      if (!excluded.has(form) && !examples[verb]?.[form]) {
        omissions.push([verb, form]);
      }
    }
  }
  return omissions;
}

const expectedCountsByForm: Partial<Record<ConjugationForm, number>> = {
  masu: 120,
  te: 120,
  ta: 120,
  nai: 119,
  potential: 96,
  passive: 70,
  causative: 99,
  conditional_ba: 118,
  conditional_tara: 120,
  volitional: 97,
  imperative: 99,
};

const intentionalOmissions: [string, ConjugationForm][] = [
  ['ある', 'potential'],
  ['ある', 'passive'],
  ['ある', 'causative'],
  ['ある', 'volitional'],
  ['ある', 'imperative'],
  ['遊ぶ', 'passive'],
  ['泳ぐ', 'passive'],
  ['渡る', 'passive'],
  ['鳴る', 'passive'],
  ['止まる', 'passive'],
  ['困る', 'passive'],
  ['頑張る', 'passive'],
  ['結婚する', 'passive'],
  ['電話する', 'passive'],
  ['洗濯する', 'passive'],
  ['勉強する', 'passive'],
  ['料理する', 'passive'],
  ['答える', 'passive'],
  ['鳴る', 'causative'],
  ['飛ぶ', 'causative'],
  ['動く', 'causative'],
  ['なくす', 'causative'],
  ['差し上げる', 'causative'],
  ['つく', 'volitional'],
  ['つく', 'imperative'],
  ['困る', 'imperative'],
  ['疲れる', 'imperative'],
  ['差し上げる', 'imperative'],
  ['くださる', 'imperative'],
  ['くれる', 'imperative'],
];

describe('N5 form example sentences', () => {
  const entries: [string, ConjugationForm, string][] = [];
  for (const [verb, forms] of Object.entries(dataset)) {
    for (const [form, sentence] of Object.entries(forms)) {
      entries.push([verb, form as ConjugationForm, sentence as string]);
    }
  }

  it('covers a non-trivial number of sentences', () => {
    expect(entries.length).toBeGreaterThan(1000);
  });

  it('matches the expected count by form', () => {
    const counts: Partial<Record<ConjugationForm, number>> = {};
    for (const [, form] of entries) {
      counts[form] = (counts[form] || 0) + 1;
    }
    expect(counts).toEqual(expectedCountsByForm);
  });

  it('only references verbs that exist in the verb list', () => {
    for (const verb of Object.keys(dataset)) {
      expect(verbs[verb]).toBeDefined();
    }
  });

  it('each sentence contains its exact conjugated form (kanji or kana)', () => {
    const offenders: string[] = [];
    for (const [verb, form, sentence] of entries) {
      const data = verbs[verb];
      const kanji = conjugate(verb, data, form).value;
      const kana = conjugateReading(data, form);
      if (!sentence.includes(kanji) && !sentence.includes(kana)) {
        offenders.push(`${verb}:${form} -> "${sentence}" (expected ${kanji}/${kana})`);
      }
    }
    expect(offenders).toEqual([]);
  });

  it('getExampleSentence returns dataset entries and undefined for omitted forms', () => {
    expect(getExampleSentence('食べる', 'volitional')).toContain('食べよう');
    for (const [verb, form] of intentionalOmissions) {
      expect(dataset[verb]?.[form]).toBeUndefined();
      expect(getExampleSentence(verb, form)).toBeUndefined();
    }
    // Unknown verb -> undefined, never throws.
    expect(getExampleSentence('存在しない動詞', 'masu')).toBeUndefined();
  });

  it('generates no examples for N5 excludeForms forms', () => {
    expectExcludedFormsAbsent('N5', dataset);
  });
});

const n4dataset = n4 as Record<string, Partial<Record<ConjugationForm, string>>>;
const n4ExpectedCountsByForm: Partial<Record<ConjugationForm, number>> = {
  masu: 173,
  te: 173,
  ta: 173,
  nai: 173,
  potential: 120,
  passive: 102,
  causative: 143,
  conditional_ba: 173,
  conditional_tara: 173,
  volitional: 131,
  imperative: 145,
};

const n4IntentionalOmissions: [string, ConjugationForm][] = [
  ['届く', 'potential'],
  ['届く', 'passive'],
  ['届く', 'volitional'],
  ['変わる', 'passive'],
  ['変わる', 'causative'],
  ['集まる', 'passive'],
  ['落ちる', 'potential'],
  ['落ちる', 'passive'],
  ['落ちる', 'causative'],
  ['落ちる', 'volitional'],
  ['壊れる', 'potential'],
  ['壊れる', 'passive'],
  ['壊れる', 'causative'],
  ['壊れる', 'volitional'],
  ['直る', 'potential'],
  ['直る', 'passive'],
  ['直る', 'causative'],
  ['直る', 'volitional'],
  ['間に合う', 'potential'],
  ['間に合う', 'passive'],
  ['間に合う', 'volitional'],
  ['間に合う', 'imperative'],
  ['続く', 'potential'],
  ['続く', 'passive'],
  ['続く', 'volitional'],
  ['続く', 'imperative'],
  ['増える', 'potential'],
  ['増える', 'passive'],
  ['増える', 'causative'],
  ['増える', 'volitional'],
  ['減る', 'potential'],
  ['減る', 'passive'],
  ['減る', 'causative'],
  ['減る', 'volitional'],
  ['決まる', 'potential'],
  ['決まる', 'volitional'],
  ['込む', 'potential'],
  ['込む', 'passive'],
  ['込む', 'causative'],
  ['込む', 'volitional'],
  ['込む', 'imperative'],
  ['向かう', 'passive'],
  ['触る', 'passive'],
  ['急ぐ', 'passive'],
  ['並ぶ', 'potential'],
  ['並ぶ', 'passive'],
  ['卒業する', 'passive'],
  ['故障する', 'potential'],
  ['故障する', 'passive'],
  ['故障する', 'volitional'],
  ['故障する', 'imperative'],
  ['出発する', 'passive'],
  ['到着する', 'passive'],
  ['賛成する', 'passive'],
  ['反対する', 'passive'],
  ['努力する', 'passive'],
  ['生活する', 'passive'],
  ['引っ越す', 'passive'],
  ['悲しむ', 'potential'],
  ['悲しむ', 'volitional'],
  ['悲しむ', 'imperative'],
  ['迷う', 'potential'],
  ['迷う', 'passive'],
  ['迷う', 'volitional'],
  ['迷う', 'imperative'],
  ['治る', 'potential'],
  ['治る', 'passive'],
  ['治る', 'causative'],
  ['治る', 'volitional'],
  ['濡れる', 'potential'],
  ['濡れる', 'passive'],
  ['濡れる', 'volitional'],
  ['濡れる', 'imperative'],
  ['願う', 'causative'],
  ['遅れる', 'potential'],
  ['遅れる', 'passive'],
  ['遅れる', 'volitional'],
  ['遅れる', 'imperative'],
  ['間違える', 'imperative'],
  ['慣れる', 'passive'],
  ['似合う', 'potential'],
  ['似合う', 'passive'],
  ['似合う', 'causative'],
  ['似合う', 'volitional'],
  ['似合う', 'imperative'],
  ['驚く', 'potential'],
  ['驚く', 'volitional'],
  ['起こる', 'potential'],
  ['起こる', 'passive'],
  ['起こる', 'causative'],
  ['起こる', 'volitional'],
  ['倒れる', 'potential'],
  ['倒れる', 'causative'],
  ['倒れる', 'volitional'],
  ['受かる', 'potential'],
  ['受かる', 'passive'],
  ['受かる', 'volitional'],
  ['感動する', 'passive'],
  ['乾く', 'potential'],
  ['乾く', 'passive'],
  ['乾く', 'causative'],
  ['乾く', 'volitional'],
  ['光る', 'potential'],
  ['光る', 'passive'],
  ['光る', 'volitional'],
  ['太る', 'passive'],
  ['痩せる', 'passive'],
  ['ぶつかる', 'potential'],
  ['ぶつかる', 'causative'],
  ['すれ違う', 'passive'],
  ['すれ違う', 'volitional'],
  ['気をつける', 'passive'],
  ['震える', 'potential'],
  ['震える', 'passive'],
  ['震える', 'volitional'],
  ['震える', 'imperative'],
  ['騙される', 'potential'],
  ['騙される', 'passive'],
  ['騙される', 'causative'],
  ['騙される', 'volitional'],
  ['騙される', 'imperative'],
  ['転がる', 'potential'],
  ['転がる', 'passive'],
  ['浮かべる', 'passive'],
  ['思い付く', 'passive'],
  ['気に入る', 'potential'],
  ['気に入る', 'volitional'],
  ['気に入る', 'imperative'],
  ['役立つ', 'potential'],
  ['役立つ', 'passive'],
  ['役立つ', 'causative'],
  ['役立つ', 'volitional'],
  ['役立つ', 'imperative'],
  ['間違う', 'potential'],
  ['間違う', 'imperative'],
  ['見つかる', 'potential'],
  ['見つかる', 'passive'],
  ['見つかる', 'causative'],
  ['見つかる', 'volitional'],
  ['生まれる', 'potential'],
  ['生まれる', 'passive'],
  ['生まれる', 'causative'],
  ['育つ', 'potential'],
  ['育つ', 'passive'],
  ['育つ', 'causative'],
  ['咲く', 'potential'],
  ['咲く', 'passive'],
  ['咲く', 'volitional'],
  ['混む', 'potential'],
  ['混む', 'causative'],
  ['混む', 'volitional'],
  ['混む', 'imperative'],
  ['訪れる', 'passive'],
  ['訪れる', 'imperative'],
  ['片寄る', 'potential'],
  ['片寄る', 'passive'],
  ['片寄る', 'volitional'],
  ['片寄る', 'imperative'],
  ['怒る', 'potential'],
  ['怒る', 'imperative'],
  ['こぼす', 'potential'],
  ['こぼす', 'volitional'],
  ['こぼす', 'imperative'],
  ['こぼれる', 'potential'],
  ['こぼれる', 'passive'],
  ['こぼれる', 'volitional'],
  ['こぼれる', 'imperative'],
  ['すべる', 'passive'],
  ['つまずく', 'potential'],
  ['つまずく', 'passive'],
  ['つまずく', 'volitional'],
  ['つまずく', 'imperative'],
  ['はしゃぐ', 'passive'],
  ['折る', 'potential'],
  ['割る', 'potential'],
];

describe('N4 form example sentences', () => {
  const entries: [string, ConjugationForm, string][] = [];
  for (const [verb, forms] of Object.entries(n4dataset)) {
    for (const [form, sentence] of Object.entries(forms)) {
      entries.push([verb, form as ConjugationForm, sentence as string]);
    }
  }

  it('covers a non-trivial number of sentences', () => {
    expect(entries.length).toBeGreaterThan(1500);
  });

  it('matches the expected count by form', () => {
    const counts: Partial<Record<ConjugationForm, number>> = {};
    for (const [, form] of entries) {
      counts[form] = (counts[form] || 0) + 1;
    }
    expect(counts).toEqual(n4ExpectedCountsByForm);
  });

  it('only references N4 verbs that exist', () => {
    for (const verb of Object.keys(n4dataset)) {
      expect(verbs[verb]).toBeDefined();
      expect(verbs[verb].jlpt).toBe('N4');
    }
  });

  it('each sentence contains its exact conjugated form (kanji or kana)', () => {
    const offenders: string[] = [];
    for (const [verb, form, sentence] of entries) {
      const data = verbs[verb];
      const kanji = conjugate(verb, data, form).value;
      const kana = conjugateReading(data, form);
      if (!sentence.includes(kanji) && !sentence.includes(kana)) {
        offenders.push(`${verb}:${form} -> "${sentence}" (expected ${kanji}/${kana})`);
      }
    }
    expect(offenders).toEqual([]);
  });

  it('generates no examples for N4 excludeForms forms', () => {
    expectExcludedFormsAbsent('N4', n4dataset);
  });

  it('omits only intentional non-exclude N4 forms', () => {
    expect(nonExcludeOmissions('N4', n4dataset)).toEqual(n4IntentionalOmissions);
  });
});

const n3dataset = n3 as Record<string, Partial<Record<ConjugationForm, string>>>;
const n3ExpectedCountsByForm: Partial<Record<ConjugationForm, number>> = {
  masu: 380,
  te: 379,
  ta: 378,
  nai: 380,
  potential: 269,
  passive: 222,
  causative: 278,
  conditional_ba: 376,
  conditional_tara: 377,
  volitional: 277,
  imperative: 258,
};

const n3IntentionalOmissions: [string, ConjugationForm][] = [
  ['得る', 'causative'],
  ['含む', 'potential'],
  ['含む', 'causative'],
  ['含む', 'volitional'],
  ['含む', 'imperative'],
  ['抱える', 'passive'],
  ['眠る', 'passive'],
  ['戦う', 'passive'],
  ['勝つ', 'passive'],
  ['負ける', 'potential'],
  ['負ける', 'passive'],
  ['負ける', 'volitional'],
  ['負ける', 'imperative'],
  ['揺れる', 'potential'],
  ['揺れる', 'passive'],
  ['揺れる', 'causative'],
  ['揺れる', 'volitional'],
  ['揺れる', 'imperative'],
  ['沈む', 'potential'],
  ['沈む', 'passive'],
  ['沈む', 'causative'],
  ['沈む', 'volitional'],
  ['沈む', 'imperative'],
  ['浮かぶ', 'potential'],
  ['浮かぶ', 'passive'],
  ['浮かぶ', 'causative'],
  ['浮かぶ', 'volitional'],
  ['浮かぶ', 'imperative'],
  ['響く', 'potential'],
  ['響く', 'passive'],
  ['響く', 'volitional'],
  ['響く', 'imperative'],
  ['輝く', 'potential'],
  ['輝く', 'passive'],
  ['輝く', 'volitional'],
  ['輝く', 'imperative'],
  ['匂う', 'potential'],
  ['匂う', 'passive'],
  ['匂う', 'volitional'],
  ['匂う', 'imperative'],
  ['成功する', 'potential'],
  ['成功する', 'passive'],
  ['成功する', 'imperative'],
  ['失敗する', 'potential'],
  ['失敗する', 'passive'],
  ['失敗する', 'volitional'],
  ['失敗する', 'imperative'],
  ['完成する', 'potential'],
  ['完成する', 'passive'],
  ['完成する', 'volitional'],
  ['完成する', 'imperative'],
  ['影響する', 'potential'],
  ['影響する', 'causative'],
  ['影響する', 'volitional'],
  ['影響する', 'imperative'],
  ['存在する', 'potential'],
  ['存在する', 'passive'],
  ['存在する', 'causative'],
  ['存在する', 'volitional'],
  ['存在する', 'imperative'],
  ['活動する', 'passive'],
  ['戻る', 'passive'],
  ['戻る', 'causative'],
  ['進む', 'potential'],
  ['進む', 'causative'],
  ['気付く', 'imperative'],
  ['重なる', 'potential'],
  ['重なる', 'passive'],
  ['重なる', 'causative'],
  ['重なる', 'volitional'],
  ['重なる', 'imperative'],
  ['伸びる', 'potential'],
  ['伸びる', 'passive'],
  ['伸びる', 'causative'],
  ['伸びる', 'volitional'],
  ['伸びる', 'imperative'],
  ['伸ばす', 'passive'],
  ['繋がる', 'potential'],
  ['繋がる', 'passive'],
  ['繋がる', 'causative'],
  ['繋がる', 'volitional'],
  ['繋がる', 'imperative'],
  ['過ぎる', 'potential'],
  ['過ぎる', 'passive'],
  ['過ぎる', 'causative'],
  ['過ぎる', 'volitional'],
  ['過ぎる', 'imperative'],
  ['預かる', 'passive'],
  ['従う', 'passive'],
  ['当たる', 'potential'],
  ['当たる', 'passive'],
  ['当たる', 'causative'],
  ['当たる', 'volitional'],
  ['温まる', 'potential'],
  ['温まる', 'passive'],
  ['温まる', 'causative'],
  ['温まる', 'imperative'],
  ['冷める', 'potential'],
  ['冷める', 'passive'],
  ['冷める', 'causative'],
  ['冷める', 'volitional'],
  ['冷める', 'imperative'],
  ['暮らす', 'passive'],
  ['暮らす', 'imperative'],
  ['叶う', 'potential'],
  ['叶う', 'passive'],
  ['叶う', 'causative'],
  ['叶う', 'volitional'],
  ['叶う', 'imperative'],
  ['悔やむ', 'potential'],
  ['悔やむ', 'causative'],
  ['悔やむ', 'volitional'],
  ['悔やむ', 'imperative'],
  ['抜く', 'potential'],
  ['抜ける', 'potential'],
  ['抜ける', 'passive'],
  ['抜ける', 'causative'],
  ['抜ける', 'volitional'],
  ['抜ける', 'imperative'],
  ['干る', 'potential'],
  ['干る', 'passive'],
  ['干る', 'causative'],
  ['干る', 'volitional'],
  ['干る', 'imperative'],
  ['散る', 'potential'],
  ['散る', 'passive'],
  ['散る', 'causative'],
  ['散る', 'volitional'],
  ['散る', 'imperative'],
  ['染まる', 'potential'],
  ['染まる', 'passive'],
  ['染まる', 'causative'],
  ['染まる', 'volitional'],
  ['染まる', 'imperative'],
  ['積もる', 'potential'],
  ['積もる', 'passive'],
  ['積もる', 'causative'],
  ['積もる', 'volitional'],
  ['積もる', 'imperative'],
  ['汚れる', 'potential'],
  ['汚れる', 'passive'],
  ['汚れる', 'causative'],
  ['汚れる', 'volitional'],
  ['汚れる', 'imperative'],
  ['溜まる', 'potential'],
  ['溜まる', 'passive'],
  ['溜まる', 'causative'],
  ['溜まる', 'volitional'],
  ['溜まる', 'imperative'],
  ['驚かす', 'causative'],
  ['沸く', 'potential'],
  ['沸く', 'passive'],
  ['沸く', 'causative'],
  ['沸く', 'volitional'],
  ['沸く', 'imperative'],
  ['映る', 'potential'],
  ['映る', 'passive'],
  ['映る', 'causative'],
  ['映る', 'volitional'],
  ['映る', 'imperative'],
  ['外れる', 'potential'],
  ['外れる', 'passive'],
  ['外れる', 'causative'],
  ['外れる', 'volitional'],
  ['外れる', 'imperative'],
  ['沿う', 'potential'],
  ['沿う', 'passive'],
  ['沿う', 'causative'],
  ['沿う', 'volitional'],
  ['沿う', 'imperative'],
  ['我慢する', 'passive'],
  ['集中する', 'passive'],
  ['緊張する', 'potential'],
  ['緊張する', 'passive'],
  ['満足する', 'passive'],
  ['後悔する', 'potential'],
  ['後悔する', 'passive'],
  ['後悔する', 'volitional'],
  ['後悔する', 'imperative'],
  ['独立する', 'passive'],
  ['成長する', 'passive'],
  ['成長する', 'imperative'],
  ['加わる', 'passive'],
  ['加わる', 'causative'],
  ['加わる', 'imperative'],
  ['向く', 'passive'],
  ['向く', 'volitional'],
  ['逃す', 'potential'],
  ['逃す', 'passive'],
  ['逃す', 'causative'],
  ['逃す', 'volitional'],
  ['広がる', 'potential'],
  ['広がる', 'passive'],
  ['広がる', 'causative'],
  ['広がる', 'volitional'],
  ['広がる', 'imperative'],
  ['深まる', 'potential'],
  ['深まる', 'passive'],
  ['深まる', 'causative'],
  ['深まる', 'volitional'],
  ['深まる', 'imperative'],
  ['回る', 'passive'],
  ['回る', 'causative'],
  ['目立つ', 'potential'],
  ['目立つ', 'passive'],
  ['目立つ', 'volitional'],
  ['目立つ', 'imperative'],
  ['申す', 'potential'],
  ['申す', 'passive'],
  ['申す', 'causative'],
  ['申す', 'volitional'],
  ['申す', 'imperative'],
  ['いただく', 'passive'],
  ['いただく', 'causative'],
  ['いただく', 'imperative'],
  ['ご覧になる', 'passive'],
  ['ご覧になる', 'causative'],
  ['ご覧になる', 'volitional'],
  ['ご覧になる', 'imperative'],
  ['召し上がる', 'potential'],
  ['召し上がる', 'passive'],
  ['召し上がる', 'causative'],
  ['召し上がる', 'volitional'],
  ['痛む', 'potential'],
  ['痛む', 'passive'],
  ['痛む', 'causative'],
  ['痛む', 'volitional'],
  ['痛む', 'imperative'],
  ['落ち着く', 'passive'],
  ['引き返す', 'passive'],
  ['引き返す', 'causative'],
  ['乗り換える', 'passive'],
  ['当てはまる', 'potential'],
  ['当てはまる', 'passive'],
  ['当てはまる', 'causative'],
  ['当てはまる', 'volitional'],
  ['当てはまる', 'imperative'],
  ['盛り上がる', 'potential'],
  ['盛り上がる', 'passive'],
  ['盛り上がる', 'causative'],
  ['盛り上がる', 'imperative'],
  ['飛び出す', 'passive'],
  ['飛び出す', 'causative'],
  ['騒がせる', 'potential'],
  ['騒がせる', 'passive'],
  ['騒がせる', 'causative'],
  ['突き当たる', 'potential'],
  ['突き当たる', 'passive'],
  ['突き当たる', 'causative'],
  ['突き当たる', 'volitional'],
  ['突き当たる', 'imperative'],
  ['食べ過ぎる', 'potential'],
  ['食べ過ぎる', 'passive'],
  ['食べ過ぎる', 'causative'],
  ['食べ過ぎる', 'volitional'],
  ['食べ過ぎる', 'imperative'],
  ['飲み過ぎる', 'potential'],
  ['飲み過ぎる', 'passive'],
  ['飲み過ぎる', 'causative'],
  ['飲み過ぎる', 'volitional'],
  ['飲み過ぎる', 'imperative'],
  ['立ち上がる', 'passive'],
  ['思い込む', 'potential'],
  ['思い込む', 'passive'],
  ['思い込む', 'volitional'],
  ['思い込む', 'imperative'],
  ['申し上げる', 'passive'],
  ['申し上げる', 'causative'],
  ['申し上げる', 'imperative'],
  ['おる', 'te'],
  ['おる', 'ta'],
  ['おる', 'nai'],
  ['おる', 'potential'],
  ['おる', 'passive'],
  ['おる', 'causative'],
  ['おる', 'conditional_ba'],
  ['おる', 'conditional_tara'],
  ['おる', 'volitional'],
  ['おる', 'imperative'],
  ['拝見する', 'passive'],
  ['拝見する', 'causative'],
  ['拝見する', 'imperative'],
  ['睨む', 'potential'],
  ['睨む', 'causative'],
  ['頷く', 'passive'],
  ['微笑む', 'potential'],
  ['微笑む', 'passive'],
  ['微笑む', 'causative'],
  ['微笑む', 'imperative'],
  ['膨らむ', 'potential'],
  ['膨らむ', 'passive'],
  ['膨らむ', 'causative'],
  ['膨らむ', 'volitional'],
  ['膨らむ', 'imperative'],
  ['縮む', 'potential'],
  ['縮む', 'passive'],
  ['縮む', 'causative'],
  ['縮む', 'volitional'],
  ['縮む', 'imperative'],
  ['膨らませる', 'causative'],
  ['閃く', 'potential'],
  ['閃く', 'passive'],
  ['閃く', 'causative'],
  ['閃く', 'volitional'],
  ['閃く', 'imperative'],
  ['惚れる', 'potential'],
  ['惚れる', 'passive'],
  ['惚れる', 'volitional'],
  ['惚れる', 'imperative'],
  ['甦る', 'potential'],
  ['甦る', 'passive'],
  ['甦る', 'volitional'],
  ['甦る', 'imperative'],
  ['弾む', 'potential'],
  ['弾む', 'passive'],
  ['弾む', 'volitional'],
  ['弾む', 'imperative'],
  ['売り切れる', 'potential'],
  ['売り切れる', 'passive'],
  ['売り切れる', 'causative'],
  ['売り切れる', 'volitional'],
  ['売り切れる', 'imperative'],
  ['入り込む', 'imperative'],
  ['行き詰まる', 'potential'],
  ['行き詰まる', 'passive'],
  ['行き詰まる', 'causative'],
  ['行き詰まる', 'volitional'],
  ['行き詰まる', 'imperative'],
  ['付き合う', 'passive'],
  ['枯れる', 'potential'],
  ['枯れる', 'passive'],
  ['枯れる', 'volitional'],
  ['枯れる', 'imperative'],
  ['腐る', 'potential'],
  ['腐る', 'passive'],
  ['腐る', 'volitional'],
  ['腐る', 'imperative'],
  ['凍る', 'potential'],
  ['凍る', 'passive'],
  ['凍る', 'volitional'],
  ['凍る', 'imperative'],
  ['溶ける', 'potential'],
  ['溶ける', 'passive'],
  ['溶ける', 'causative'],
  ['溶ける', 'volitional'],
  ['溶ける', 'imperative'],
  ['明ける', 'potential'],
  ['明ける', 'passive'],
  ['明ける', 'causative'],
  ['明ける', 'volitional'],
  ['明ける', 'imperative'],
  ['暮れる', 'potential'],
  ['暮れる', 'passive'],
  ['暮れる', 'causative'],
  ['暮れる', 'volitional'],
  ['暮れる', 'imperative'],
  ['居眠りする', 'potential'],
  ['居眠りする', 'passive'],
  ['居眠りする', 'volitional'],
  ['居眠りする', 'imperative'],
  ['油断する', 'potential'],
  ['油断する', 'passive'],
  ['油断する', 'volitional'],
  ['油断する', 'imperative'],
  ['辿り着く', 'passive'],
  ['辿り着く', 'causative'],
  ['差し掛かる', 'potential'],
  ['差し掛かる', 'passive'],
  ['差し掛かる', 'causative'],
  ['差し掛かる', 'volitional'],
  ['差し掛かる', 'imperative'],
  ['着替える', 'passive'],
  ['浮き上がる', 'potential'],
  ['浮き上がる', 'passive'],
  ['浮き上がる', 'causative'],
  ['浮き上がる', 'volitional'],
  ['浮き上がる', 'imperative'],
  ['発足する', 'passive'],
  ['発足する', 'volitional'],
  ['発足する', 'imperative'],
  ['対立する', 'potential'],
  ['対立する', 'passive'],
  ['対立する', 'volitional'],
  ['対立する', 'imperative'],
  ['協力する', 'passive'],
  ['競争する', 'passive'],
  ['参る', 'potential'],
  ['参る', 'passive'],
  ['参る', 'causative'],
  ['存じる', 'ta'],
  ['存じる', 'potential'],
  ['存じる', 'passive'],
  ['存じる', 'causative'],
  ['存じる', 'conditional_ba'],
  ['存じる', 'conditional_tara'],
  ['存じる', 'volitional'],
  ['存じる', 'imperative'],
  ['溢れ出す', 'potential'],
  ['溢れ出す', 'passive'],
  ['溢れ出す', 'causative'],
  ['溢れ出す', 'volitional'],
  ['溢れ出す', 'imperative'],
  ['切り抜ける', 'passive'],
  ['張り切る', 'potential'],
  ['張り切る', 'passive'],
  ['振り向く', 'potential'],
  ['打ち勝つ', 'passive'],
  ['立ち止まる', 'passive'],
  ['出会う', 'passive'],
  ['出会う', 'causative'],
  ['出会う', 'imperative'],
  ['噛み締める', 'passive'],
  ['起き上がる', 'passive'],
  ['締まる', 'potential'],
  ['締まる', 'passive'],
  ['締まる', 'causative'],
  ['締まる', 'volitional'],
  ['締まる', 'imperative'],
  ['緩む', 'potential'],
  ['緩む', 'passive'],
  ['緩む', 'causative'],
  ['緩む', 'volitional'],
  ['緩む', 'imperative'],
  ['栄える', 'potential'],
  ['栄える', 'passive'],
  ['栄える', 'causative'],
  ['栄える', 'volitional'],
  ['栄える', 'imperative'],
  ['錆びる', 'potential'],
  ['錆びる', 'passive'],
  ['錆びる', 'causative'],
  ['錆びる', 'volitional'],
  ['錆びる', 'imperative'],
  ['納得する', 'passive'],
  ['納得する', 'volitional'],
  ['納得する', 'imperative'],
  ['察する', 'potential'],
  ['察する', 'passive'],
  ['察する', 'causative'],
  ['察する', 'imperative'],
  ['適する', 'conditional_tara'],
  ['思い至る', 'potential'],
  ['思い至る', 'passive'],
  ['思い至る', 'causative'],
  ['思い至る', 'volitional'],
  ['思い至る', 'imperative'],
  ['立ち回る', 'passive'],
  ['立ち直る', 'passive'],
  ['立ちはだかる', 'potential'],
  ['立ちはだかる', 'passive'],
  ['立ちはだかる', 'causative'],
  ['立ちはだかる', 'volitional'],
  ['立ちはだかる', 'imperative'],
  ['擦れ違う', 'passive'],
  ['擦れ違う', 'causative'],
  ['擦れ違う', 'volitional'],
  ['擦れ違う', 'imperative'],
  ['言い争う', 'volitional'],
  ['言い争う', 'imperative'],
  ['入れ替わる', 'potential'],
  ['入れ替わる', 'passive'],
  ['入れ替わる', 'causative'],
  ['入れ替わる', 'volitional'],
  ['入れ替わる', 'imperative'],
  ['吹き出す', 'potential'],
  ['吹き出す', 'passive'],
  ['吹き出す', 'causative'],
  ['吹き出す', 'volitional'],
  ['吹き出す', 'imperative'],
  ['見出す', 'causative'],
  ['見出す', 'volitional'],
  ['見出す', 'imperative'],
  ['講演する', 'passive'],
  ['講演する', 'imperative'],
  ['合意する', 'passive'],
  ['合意する', 'imperative'],
  ['決裂する', 'potential'],
  ['決裂する', 'passive'],
  ['決裂する', 'causative'],
  ['決裂する', 'volitional'],
  ['決裂する', 'imperative'],
  ['妥結する', 'potential'],
  ['妥結する', 'passive'],
  ['妥結する', 'causative'],
  ['妥結する', 'volitional'],
  ['妥結する', 'imperative'],
  ['所有する', 'volitional'],
  ['所有する', 'imperative'],
  ['譲り合う', 'passive'],
  ['剥ける', 'potential'],
  ['剥ける', 'passive'],
  ['剥ける', 'causative'],
  ['剥ける', 'volitional'],
  ['剥ける', 'imperative'],
  ['すくむ', 'potential'],
  ['すくむ', 'passive'],
  ['すくむ', 'causative'],
  ['すくむ', 'volitional'],
  ['すくむ', 'imperative'],
  ['ずれる', 'potential'],
  ['ずれる', 'passive'],
  ['ずれる', 'causative'],
  ['ずれる', 'volitional'],
  ['ずれる', 'imperative'],
  ['はみ出す', 'potential'],
  ['はみ出す', 'passive'],
  ['はみ出す', 'causative'],
  ['はみ出す', 'volitional'],
  ['はみ出す', 'imperative'],
  ['のめり込む', 'potential'],
  ['のめり込む', 'passive'],
  ['のめり込む', 'causative'],
  ['のめり込む', 'imperative'],
  ['のさばる', 'potential'],
  ['のさばる', 'passive'],
  ['のさばる', 'causative'],
  ['のさばる', 'volitional'],
  ['のさばる', 'imperative'],
  ['ぼやく', 'potential'],
  ['ぼやく', 'passive'],
  ['ぼやく', 'causative'],
  ['ぼやく', 'conditional_ba'],
  ['ぼやく', 'imperative'],
  ['たかる', 'potential'],
  ['たかる', 'volitional'],
  ['たかる', 'imperative'],
  ['ぐずる', 'potential'],
  ['ぐずる', 'passive'],
  ['ぐずる', 'causative'],
  ['ぐずる', 'volitional'],
  ['ぐずる', 'imperative'],
  ['すがる', 'passive'],
  ['すがる', 'imperative'],
  ['まごつく', 'potential'],
  ['まごつく', 'passive'],
  ['まごつく', 'causative'],
  ['まごつく', 'volitional'],
  ['まごつく', 'imperative'],
  ['たじろぐ', 'potential'],
  ['たじろぐ', 'passive'],
  ['たじろぐ', 'causative'],
  ['たじろぐ', 'volitional'],
  ['たじろぐ', 'imperative'],
  ['うろつく', 'volitional'],
  ['うろつく', 'imperative'],
  ['志す', 'passive'],
  ['志す', 'causative'],
  ['見届ける', 'passive'],
  ['分かち合う', 'passive'],
  ['語り合う', 'passive'],
  ['語り合う', 'imperative'],
  ['認め合う', 'passive'],
  ['認め合う', 'imperative'],
  ['補い合う', 'passive'],
  ['補い合う', 'imperative'],
  ['高め合う', 'passive'],
  ['競い合う', 'passive'],
  ['支持する', 'imperative'],
  ['物足りる', 'masu'],
  ['物足りる', 'te'],
  ['物足りる', 'ta'],
  ['物足りる', 'potential'],
  ['物足りる', 'passive'],
  ['物足りる', 'causative'],
  ['物足りる', 'conditional_ba'],
  ['物足りる', 'conditional_tara'],
  ['物足りる', 'volitional'],
  ['物足りる', 'imperative'],
  ['恥じる', 'potential'],
  ['恥じる', 'passive'],
  ['恥じる', 'imperative'],
  ['恥じらう', 'potential'],
  ['恥じらう', 'passive'],
  ['恥じらう', 'causative'],
  ['恥じらう', 'conditional_ba'],
  ['恥じらう', 'volitional'],
  ['恥じらう', 'imperative'],
  ['損なう', 'potential'],
  ['損なう', 'causative'],
  ['損なう', 'imperative'],
  ['損ねる', 'potential'],
  ['損ねる', 'passive'],
  ['損ねる', 'causative'],
  ['損ねる', 'volitional'],
  ['損ねる', 'imperative'],
  ['余る', 'potential'],
  ['余る', 'passive'],
  ['余る', 'volitional'],
  ['余る', 'imperative'],
];

describe('N3 form example sentences', () => {
  const entries: [string, ConjugationForm, string][] = [];
  for (const [verb, forms] of Object.entries(n3dataset)) {
    for (const [form, sentence] of Object.entries(forms)) {
      entries.push([verb, form as ConjugationForm, sentence as string]);
    }
  }

  it('covers a non-trivial number of sentences', () => {
    expect(entries.length).toBeGreaterThan(3000);
  });

  it('matches the expected count by form', () => {
    const counts: Partial<Record<ConjugationForm, number>> = {};
    for (const [, form] of entries) {
      counts[form] = (counts[form] || 0) + 1;
    }
    expect(counts).toEqual(n3ExpectedCountsByForm);
  });

  it('only references N3 verbs that exist', () => {
    for (const verb of Object.keys(n3dataset)) {
      expect(verbs[verb]).toBeDefined();
      expect(verbs[verb].jlpt).toBe('N3');
    }
  });

  it('each sentence contains its exact conjugated form (kanji or kana)', () => {
    const offenders: string[] = [];
    for (const [verb, form, sentence] of entries) {
      const data = verbs[verb];
      const kanji = conjugate(verb, data, form).value;
      const kana = conjugateReading(data, form);
      if (!sentence.includes(kanji) && !sentence.includes(kana)) {
        offenders.push(`${verb}:${form} -> "${sentence}" (expected ${kanji}/${kana})`);
      }
    }
    expect(offenders).toEqual([]);
  });

  it('generates no examples for N3 excludeForms forms', () => {
    expectExcludedFormsAbsent('N3', n3dataset);
  });

  it('omits only intentional non-exclude N3 forms', () => {
    expect(nonExcludeOmissions('N3', n3dataset)).toEqual(n3IntentionalOmissions);
  });
});

const n1dataset = n1 as Record<string, Partial<Record<ConjugationForm, string>>>;
const n1ExpectedCountsByForm: Partial<Record<ConjugationForm, number>> = {
  masu: 566,
  te: 568,
  ta: 568,
  nai: 558,
  potential: 293,
  passive: 306,
  causative: 278,
  conditional_ba: 566,
  conditional_tara: 566,
  volitional: 292,
  imperative: 240,
};

const n1IntentionalOmissions: [string, ConjugationForm][] = [
  ['滅びる', 'potential'],
  ['滅びる', 'passive'],
  ['滅びる', 'causative'],
  ['滅びる', 'volitional'],
  ['滅びる', 'imperative'],
  ['崇める', 'potential'],
  ['崇める', 'causative'],
  ['崇める', 'volitional'],
  ['崇める', 'imperative'],
  ['侮る', 'causative'],
  ['侮る', 'volitional'],
  ['侮る', 'imperative'],
  ['怠る', 'potential'],
  ['怠る', 'causative'],
  ['怠る', 'volitional'],
  ['怠る', 'imperative'],
  ['阻む', 'potential'],
  ['阻む', 'causative'],
  ['阻む', 'volitional'],
  ['阻む', 'imperative'],
  ['潤む', 'potential'],
  ['潤む', 'passive'],
  ['潤む', 'conditional_ba'],
  ['潤む', 'volitional'],
  ['潤む', 'imperative'],
  ['覆る', 'potential'],
  ['覆る', 'passive'],
  ['覆る', 'causative'],
  ['覆る', 'volitional'],
  ['覆る', 'imperative'],
  ['揺るがす', 'causative'],
  ['脅かす', 'causative'],
  ['儲ける', 'passive'],
  ['儲ける', 'causative'],
  ['携わる', 'passive'],
  ['携わる', 'causative'],
  ['携わる', 'imperative'],
  ['見据える', 'passive'],
  ['見据える', 'causative'],
  ['見極める', 'passive'],
  ['立ち向かう', 'passive'],
  ['突き詰める', 'passive'],
  ['思い切る', 'passive'],
  ['思い切る', 'causative'],
  ['差し支える', 'potential'],
  ['差し支える', 'passive'],
  ['差し支える', 'causative'],
  ['差し支える', 'volitional'],
  ['差し支える', 'imperative'],
  ['見落とす', 'volitional'],
  ['見落とす', 'imperative'],
  ['取り組む', 'passive'],
  ['振り返る', 'passive'],
  ['乗り越える', 'passive'],
  ['紛れる', 'potential'],
  ['紛れる', 'passive'],
  ['紛れる', 'causative'],
  ['紛れる', 'volitional'],
  ['紛れる', 'imperative'],
  ['寄与する', 'passive'],
  ['寄与する', 'causative'],
  ['寄与する', 'volitional'],
  ['寄与する', 'imperative'],
  ['該当する', 'potential'],
  ['該当する', 'passive'],
  ['該当する', 'causative'],
  ['該当する', 'volitional'],
  ['該当する', 'imperative'],
  ['喚起する', 'causative'],
  ['充実する', 'potential'],
  ['充実する', 'passive'],
  ['充実する', 'causative'],
  ['充実する', 'volitional'],
  ['充実する', 'imperative'],
  ['普及する', 'potential'],
  ['普及する', 'passive'],
  ['普及する', 'volitional'],
  ['普及する', 'imperative'],
  ['衰退する', 'potential'],
  ['衰退する', 'passive'],
  ['衰退する', 'volitional'],
  ['衰退する', 'imperative'],
  ['浸透する', 'potential'],
  ['浸透する', 'passive'],
  ['浸透する', 'volitional'],
  ['浸透する', 'imperative'],
  ['添える', 'passive'],
  ['朽ちる', 'potential'],
  ['朽ちる', 'passive'],
  ['朽ちる', 'causative'],
  ['朽ちる', 'volitional'],
  ['朽ちる', 'imperative'],
  ['虐げる', 'volitional'],
  ['虐げる', 'imperative'],
  ['匹敵する', 'potential'],
  ['匹敵する', 'passive'],
  ['匹敵する', 'causative'],
  ['匹敵する', 'volitional'],
  ['匹敵する', 'imperative'],
  ['逸脱する', 'passive'],
  ['逸脱する', 'volitional'],
  ['逸脱する', 'imperative'],
  ['陥る', 'potential'],
  ['陥る', 'passive'],
  ['陥る', 'volitional'],
  ['陥る', 'imperative'],
  ['施行する', 'imperative'],
  ['抗う', 'passive'],
  ['抗う', 'causative'],
  ['労う', 'imperative'],
  ['憂う', 'potential'],
  ['憂う', 'passive'],
  ['憂う', 'causative'],
  ['憂う', 'volitional'],
  ['憂う', 'imperative'],
  ['装う', 'imperative'],
  ['廃る', 'potential'],
  ['廃る', 'passive'],
  ['廃る', 'causative'],
  ['廃る', 'volitional'],
  ['廃る', 'imperative'],
  ['見下す', 'volitional'],
  ['見下す', 'imperative'],
  ['見合わせる', 'imperative'],
  ['立ち寄る', 'passive'],
  ['食い止める', 'potential'],
  ['書き留める', 'potential'],
  ['巻き込む', 'imperative'],
  ['成り立つ', 'potential'],
  ['成り立つ', 'passive'],
  ['成り立つ', 'volitional'],
  ['成り立つ', 'imperative'],
  ['溶け込む', 'passive'],
  ['溶け込む', 'causative'],
  ['思い知る', 'potential'],
  ['思い知る', 'passive'],
  ['思い知る', 'volitional'],
  ['歩み寄る', 'passive'],
  ['歩み寄る', 'causative'],
  ['思い遣る', 'potential'],
  ['思い遣る', 'passive'],
  ['思い遣る', 'causative'],
  ['思い遣る', 'volitional'],
  ['思い遣る', 'imperative'],
  ['申し出る', 'causative'],
  ['申し出る', 'imperative'],
  ['弁える', 'passive'],
  ['纏まる', 'potential'],
  ['纏まる', 'passive'],
  ['纏まる', 'causative'],
  ['纏まる', 'volitional'],
  ['纏まる', 'imperative'],
  ['没頭する', 'passive'],
  ['破綻する', 'potential'],
  ['破綻する', 'passive'],
  ['破綻する', 'causative'],
  ['破綻する', 'volitional'],
  ['破綻する', 'imperative'],
  ['変遷する', 'potential'],
  ['変遷する', 'passive'],
  ['変遷する', 'causative'],
  ['変遷する', 'volitional'],
  ['変遷する', 'imperative'],
  ['頓挫する', 'potential'],
  ['頓挫する', 'passive'],
  ['頓挫する', 'causative'],
  ['頓挫する', 'volitional'],
  ['頓挫する', 'imperative'],
  ['奔走する', 'passive'],
  ['暗躍する', 'passive'],
  ['暗躍する', 'causative'],
  ['暗躍する', 'imperative'],
  ['逡巡する', 'potential'],
  ['逡巡する', 'passive'],
  ['逡巡する', 'causative'],
  ['逡巡する', 'volitional'],
  ['逡巡する', 'imperative'],
  ['懐く', 'potential'],
  ['懐く', 'volitional'],
  ['懐く', 'imperative'],
  ['見紛う', 'potential'],
  ['見紛う', 'passive'],
  ['見紛う', 'causative'],
  ['見紛う', 'volitional'],
  ['見紛う', 'imperative'],
  ['思い巡らす', 'passive'],
  ['思い巡らす', 'causative'],
  ['言い逃れる', 'passive'],
  ['踏み切る', 'passive'],
  ['踏み切る', 'causative'],
  ['踏み留まる', 'potential'],
  ['踏み留まる', 'passive'],
  ['踏み留まる', 'causative'],
  ['塞がる', 'potential'],
  ['塞がる', 'passive'],
  ['塞がる', 'causative'],
  ['塞がる', 'volitional'],
  ['塞がる', 'imperative'],
  ['嵩む', 'potential'],
  ['嵩む', 'passive'],
  ['嵩む', 'causative'],
  ['嵩む', 'volitional'],
  ['嵩む', 'imperative'],
  ['群がる', 'potential'],
  ['群がる', 'passive'],
  ['群がる', 'causative'],
  ['群がる', 'volitional'],
  ['挫ける', 'potential'],
  ['挫ける', 'passive'],
  ['挫ける', 'causative'],
  ['挫ける', 'volitional'],
  ['挫ける', 'imperative'],
  ['陶酔する', 'potential'],
  ['陶酔する', 'passive'],
  ['陶酔する', 'volitional'],
  ['陶酔する', 'imperative'],
  ['葛藤する', 'potential'],
  ['葛藤する', 'passive'],
  ['葛藤する', 'causative'],
  ['葛藤する', 'volitional'],
  ['葛藤する', 'imperative'],
  ['躊躇する', 'passive'],
  ['収斂する', 'potential'],
  ['収斂する', 'passive'],
  ['収斂する', 'volitional'],
  ['収斂する', 'imperative'],
  ['堪能する', 'passive'],
  ['居座る', 'potential'],
  ['居座る', 'volitional'],
  ['寝そべる', 'passive'],
  ['纏わる', 'potential'],
  ['纏わる', 'passive'],
  ['纏わる', 'causative'],
  ['纏わる', 'volitional'],
  ['纏わる', 'imperative'],
  ['跪く', 'passive'],
  ['顧みる', 'passive'],
  ['顧みる', 'imperative'],
  ['翻弄する', 'causative'],
  ['翻弄する', 'imperative'],
  ['傾倒する', 'potential'],
  ['傾倒する', 'passive'],
  ['傾倒する', 'causative'],
  ['傾倒する', 'volitional'],
  ['傾倒する', 'imperative'],
  ['嘱託する', 'causative'],
  ['嘱託する', 'volitional'],
  ['嘱託する', 'imperative'],
  ['享受する', 'causative'],
  ['享受する', 'volitional'],
  ['享受する', 'imperative'],
  ['標榜する', 'causative'],
  ['標榜する', 'volitional'],
  ['標榜する', 'imperative'],
  ['献身する', 'potential'],
  ['献身する', 'passive'],
  ['献身する', 'causative'],
  ['献身する', 'imperative'],
  ['憤慨する', 'potential'],
  ['憤慨する', 'passive'],
  ['憤慨する', 'causative'],
  ['憤慨する', 'volitional'],
  ['憤慨する', 'imperative'],
  ['慟哭する', 'potential'],
  ['慟哭する', 'passive'],
  ['慟哭する', 'causative'],
  ['慟哭する', 'volitional'],
  ['慟哭する', 'imperative'],
  ['殉じる', 'potential'],
  ['殉じる', 'passive'],
  ['殉じる', 'causative'],
  ['殉じる', 'imperative'],
  ['篭もる', 'passive'],
  ['蹲る', 'passive'],
  ['蹲る', 'causative'],
  ['蹲る', 'volitional'],
  ['蹲る', 'imperative'],
  ['膝まずく', 'potential'],
  ['膝まずく', 'passive'],
  ['膝まずく', 'causative'],
  ['膝まずく', 'volitional'],
  ['宥める', 'passive'],
  ['諫める', 'passive'],
  ['戒める', 'passive'],
  ['物語る', 'potential'],
  ['物語る', 'passive'],
  ['物語る', 'causative'],
  ['物語る', 'volitional'],
  ['物語る', 'imperative'],
  ['言い含める', 'passive'],
  ['言い寄る', 'imperative'],
  ['纏い付く', 'potential'],
  ['纏い付く', 'passive'],
  ['纏い付く', 'causative'],
  ['纏い付く', 'volitional'],
  ['纏い付く', 'imperative'],
  ['蔓延る', 'potential'],
  ['蔓延る', 'passive'],
  ['蔓延る', 'causative'],
  ['蔓延る', 'volitional'],
  ['蔓延る', 'imperative'],
  ['擦り減る', 'potential'],
  ['擦り減る', 'passive'],
  ['擦り減る', 'causative'],
  ['擦り減る', 'volitional'],
  ['擦り減る', 'imperative'],
  ['凋む', 'potential'],
  ['凋む', 'passive'],
  ['凋む', 'causative'],
  ['凋む', 'volitional'],
  ['凋む', 'imperative'],
  ['澄む', 'potential'],
  ['澄む', 'passive'],
  ['澄む', 'causative'],
  ['澄む', 'volitional'],
  ['澄む', 'imperative'],
  ['澄ます', 'potential'],
  ['澄ます', 'passive'],
  ['澄ます', 'causative'],
  ['澄ます', 'volitional'],
  ['燻る', 'potential'],
  ['燻る', 'passive'],
  ['燻る', 'causative'],
  ['燻る', 'volitional'],
  ['燻る', 'imperative'],
  ['翳る', 'potential'],
  ['翳る', 'passive'],
  ['翳る', 'causative'],
  ['翳る', 'volitional'],
  ['翳る', 'imperative'],
  ['佇まう', 'potential'],
  ['佇まう', 'passive'],
  ['佇まう', 'causative'],
  ['佇まう', 'volitional'],
  ['佇まう', 'imperative'],
  ['散逸する', 'potential'],
  ['散逸する', 'passive'],
  ['散逸する', 'causative'],
  ['散逸する', 'volitional'],
  ['散逸する', 'imperative'],
  ['廃れる', 'potential'],
  ['廃れる', 'passive'],
  ['廃れる', 'causative'],
  ['廃れる', 'volitional'],
  ['廃れる', 'imperative'],
  ['潤う', 'potential'],
  ['潤う', 'passive'],
  ['潤う', 'causative'],
  ['潤う', 'volitional'],
  ['潤う', 'imperative'],
  ['佩く', 'potential'],
  ['佩く', 'volitional'],
  ['佩く', 'imperative'],
  ['鎮まる', 'potential'],
  ['鎮まる', 'passive'],
  ['鎮まる', 'causative'],
  ['鎮まる', 'volitional'],
  ['賜る', 'nai'],
  ['賜る', 'potential'],
  ['賜る', 'passive'],
  ['賜る', 'causative'],
  ['賜る', 'volitional'],
  ['賜る', 'imperative'],
  ['報いる', 'potential'],
  ['報いる', 'causative'],
  ['報いる', 'volitional'],
  ['報いる', 'imperative'],
  ['鑑みる', 'nai'],
  ['鑑みる', 'potential'],
  ['鑑みる', 'passive'],
  ['鑑みる', 'causative'],
  ['鑑みる', 'volitional'],
  ['鑑みる', 'imperative'],
  ['見受ける', 'nai'],
  ['見受ける', 'potential'],
  ['見受ける', 'causative'],
  ['見受ける', 'volitional'],
  ['見受ける', 'imperative'],
  ['案じる', 'potential'],
  ['案じる', 'causative'],
  ['案じる', 'volitional'],
  ['案じる', 'imperative'],
  ['免じる', 'nai'],
  ['免じる', 'potential'],
  ['免じる', 'passive'],
  ['免じる', 'causative'],
  ['免じる', 'volitional'],
  ['免じる', 'imperative'],
  ['呈する', 'potential'],
  ['呈する', 'imperative'],
  ['有する', 'potential'],
  ['有する', 'passive'],
  ['有する', 'causative'],
  ['有する', 'volitional'],
  ['有する', 'imperative'],
  ['擁する', 'potential'],
  ['擁する', 'passive'],
  ['擁する', 'causative'],
  ['擁する', 'volitional'],
  ['擁する', 'imperative'],
  ['逸する', 'potential'],
  ['逸する', 'passive'],
  ['逸する', 'causative'],
  ['逸する', 'volitional'],
  ['逸する', 'imperative'],
  ['奉じる', 'potential'],
  ['奉じる', 'causative'],
  ['奉じる', 'volitional'],
  ['奉じる', 'imperative'],
  ['糺す', 'causative'],
  ['糺す', 'volitional'],
  ['征する', 'potential'],
  ['征する', 'causative'],
  ['画策する', 'imperative'],
  ['慄く', 'potential'],
  ['慄く', 'passive'],
  ['慄く', 'volitional'],
  ['慄く', 'imperative'],
  ['僻む', 'potential'],
  ['僻む', 'volitional'],
  ['僻む', 'imperative'],
  ['諂う', 'passive'],
  ['媚びる', 'potential'],
  ['媚びる', 'passive'],
  ['喰らう', 'passive'],
  ['練り歩く', 'passive'],
  ['齎す', 'potential'],
  ['齎す', 'causative'],
  ['齎す', 'volitional'],
  ['齎す', 'imperative'],
  ['虐める', 'volitional'],
  ['虐める', 'imperative'],
  ['靡かす', 'passive'],
  ['煽てる', 'imperative'],
  ['窶す', 'potential'],
  ['窶す', 'passive'],
  ['窶す', 'causative'],
  ['窶す', 'volitional'],
  ['窶す', 'imperative'],
  ['綻びる', 'potential'],
  ['綻びる', 'passive'],
  ['綻びる', 'causative'],
  ['綻びる', 'volitional'],
  ['綻びる', 'imperative'],
  ['纏う', 'passive'],
  ['蕩ける', 'potential'],
  ['蕩ける', 'passive'],
  ['蕩ける', 'causative'],
  ['蕩ける', 'volitional'],
  ['蕩ける', 'imperative'],
  ['嗤う', 'volitional'],
  ['嗤う', 'imperative'],
  ['誑かす', 'volitional'],
  ['誑かす', 'imperative'],
  ['唸る', 'potential'],
  ['唸る', 'passive'],
  ['唸る', 'volitional'],
  ['唸る', 'imperative'],
  ['吠える', 'potential'],
  ['吠える', 'volitional'],
  ['噎ぶ', 'potential'],
  ['噎ぶ', 'passive'],
  ['噎ぶ', 'causative'],
  ['噎ぶ', 'volitional'],
  ['噎ぶ', 'imperative'],
  ['喘ぐ', 'potential'],
  ['喘ぐ', 'passive'],
  ['喘ぐ', 'volitional'],
  ['喘ぐ', 'imperative'],
  ['呻く', 'potential'],
  ['呻く', 'passive'],
  ['呻く', 'volitional'],
  ['呻く', 'imperative'],
  ['噎せる', 'potential'],
  ['噎せる', 'passive'],
  ['噎せる', 'causative'],
  ['噎せる', 'volitional'],
  ['噎せる', 'imperative'],
  ['嘯く', 'potential'],
  ['嘯く', 'causative'],
  ['嘯く', 'volitional'],
  ['嘯く', 'imperative'],
  ['誹る', 'volitional'],
  ['誹る', 'imperative'],
  ['贖う', 'imperative'],
  ['弑する', 'potential'],
  ['弑する', 'causative'],
  ['弑する', 'volitional'],
  ['弑する', 'imperative'],
  ['禅譲する', 'imperative'],
  ['簒奪する', 'imperative'],
  ['粛正する', 'imperative'],
  ['瞑想する', 'passive'],
  ['懇願する', 'imperative'],
  ['慨嘆する', 'potential'],
  ['慨嘆する', 'passive'],
  ['慨嘆する', 'causative'],
  ['慨嘆する', 'volitional'],
  ['慨嘆する', 'imperative'],
  ['逼迫する', 'potential'],
  ['逼迫する', 'passive'],
  ['逼迫する', 'causative'],
  ['逼迫する', 'volitional'],
  ['逼迫する', 'imperative'],
  ['枯渇する', 'potential'],
  ['枯渇する', 'passive'],
  ['枯渇する', 'volitional'],
  ['枯渇する', 'imperative'],
  ['形骸化する', 'potential'],
  ['形骸化する', 'passive'],
  ['形骸化する', 'volitional'],
  ['形骸化する', 'imperative'],
  ['風化する', 'potential'],
  ['風化する', 'passive'],
  ['風化する', 'volitional'],
  ['風化する', 'imperative'],
  ['陳腐化する', 'potential'],
  ['陳腐化する', 'passive'],
  ['陳腐化する', 'volitional'],
  ['陳腐化する', 'imperative'],
  ['失墜する', 'potential'],
  ['失墜する', 'passive'],
  ['失墜する', 'volitional'],
  ['失墜する', 'imperative'],
  ['凋落する', 'potential'],
  ['凋落する', 'passive'],
  ['凋落する', 'causative'],
  ['凋落する', 'volitional'],
  ['凋落する', 'imperative'],
  ['跋扈する', 'potential'],
  ['跋扈する', 'passive'],
  ['跋扈する', 'causative'],
  ['跋扈する', 'volitional'],
  ['跋扈する', 'imperative'],
  ['横行する', 'potential'],
  ['横行する', 'passive'],
  ['横行する', 'volitional'],
  ['横行する', 'imperative'],
  ['轟く', 'potential'],
  ['轟く', 'passive'],
  ['轟く', 'causative'],
  ['轟く', 'volitional'],
  ['轟く', 'imperative'],
  ['轟かす', 'passive'],
  ['轟かす', 'causative'],
  ['霞む', 'potential'],
  ['霞む', 'passive'],
  ['霞む', 'causative'],
  ['霞む', 'volitional'],
  ['霞む', 'imperative'],
  ['滴る', 'potential'],
  ['滴る', 'passive'],
  ['滴る', 'causative'],
  ['滴る', 'volitional'],
  ['滴る', 'imperative'],
  ['煌めく', 'potential'],
  ['煌めく', 'passive'],
  ['煌めく', 'causative'],
  ['煌めく', 'volitional'],
  ['煌めく', 'imperative'],
  ['揺蕩う', 'potential'],
  ['揺蕩う', 'passive'],
  ['揺蕩う', 'causative'],
  ['揺蕩う', 'volitional'],
  ['揺蕩う', 'imperative'],
  ['靡く', 'potential'],
  ['靡く', 'passive'],
  ['靡く', 'volitional'],
  ['靡く', 'imperative'],
  ['鬩ぎ合う', 'potential'],
  ['鬩ぎ合う', 'passive'],
  ['鬩ぎ合う', 'causative'],
  ['鬩ぎ合う', 'volitional'],
  ['鬩ぎ合う', 'imperative'],
  ['翻る', 'potential'],
  ['翻る', 'passive'],
  ['翻る', 'causative'],
  ['翻る', 'volitional'],
  ['翻る', 'imperative'],
  ['穿つ', 'causative'],
  ['穿つ', 'volitional'],
  ['穿つ', 'imperative'],
  ['荒む', 'potential'],
  ['荒む', 'passive'],
  ['荒む', 'causative'],
  ['荒む', 'volitional'],
  ['荒む', 'imperative'],
  ['荒ぶる', 'potential'],
  ['荒ぶる', 'passive'],
  ['荒ぶる', 'causative'],
  ['荒ぶる', 'volitional'],
  ['荒ぶる', 'imperative'],
  ['嘶く', 'potential'],
  ['嘶く', 'passive'],
  ['嘶く', 'causative'],
  ['嘶く', 'volitional'],
  ['嘶く', 'imperative'],
  ['轢く', 'potential'],
  ['轢く', 'volitional'],
  ['轢く', 'imperative'],
  ['漲らす', 'passive'],
  ['漲らす', 'causative'],
  ['漲らす', 'imperative'],
  ['蝕まれる', 'potential'],
  ['蝕まれる', 'passive'],
  ['蝕まれる', 'causative'],
  ['蝕まれる', 'volitional'],
  ['蝕まれる', 'imperative'],
  ['陶冶する', 'imperative'],
  ['醸す', 'causative'],
  ['醸す', 'imperative'],
  ['慮る', 'volitional'],
  ['慮る', 'imperative'],
  ['忖度する', 'imperative'],
  ['喚く', 'passive'],
  ['喚く', 'imperative'],
  ['蠢く', 'potential'],
  ['蠢く', 'passive'],
  ['蠢く', 'causative'],
  ['蠢く', 'volitional'],
  ['蠢く', 'imperative'],
  ['這う', 'potential'],
  ['這い上がる', 'passive'],
  ['舞う', 'passive'],
  ['奏する', 'potential'],
  ['奏する', 'causative'],
  ['罷り通る', 'potential'],
  ['罷り通る', 'passive'],
  ['罷り通る', 'causative'],
  ['罷り通る', 'volitional'],
  ['罷り通る', 'imperative'],
  ['憚る', 'potential'],
  ['憚る', 'causative'],
  ['憚る', 'volitional'],
  ['憚る', 'imperative'],
  ['蔑する', 'potential'],
  ['蔑する', 'causative'],
  ['蔑する', 'volitional'],
  ['蔑する', 'imperative'],
  ['弄する', 'potential'],
  ['弄する', 'causative'],
  ['弄する', 'volitional'],
  ['弄する', 'imperative'],
  ['堕する', 'potential'],
  ['堕する', 'passive'],
  ['堕する', 'causative'],
  ['堕する', 'volitional'],
  ['堕する', 'imperative'],
  ['帰する', 'potential'],
  ['帰する', 'passive'],
  ['帰する', 'causative'],
  ['帰する', 'volitional'],
  ['帰する', 'imperative'],
  ['資する', 'potential'],
  ['資する', 'passive'],
  ['資する', 'causative'],
  ['資する', 'volitional'],
  ['資する', 'imperative'],
  ['処する', 'potential'],
  ['処する', 'causative'],
  ['処する', 'volitional'],
  ['処する', 'imperative'],
  ['服する', 'potential'],
  ['服する', 'passive'],
  ['服する', 'causative'],
  ['服する', 'volitional'],
  ['服する', 'imperative'],
  ['則する', 'masu'],
  ['則する', 'potential'],
  ['則する', 'passive'],
  ['則する', 'causative'],
  ['則する', 'volitional'],
  ['則する', 'imperative'],
  ['抗する', 'potential'],
  ['抗する', 'passive'],
  ['抗する', 'causative'],
  ['抗する', 'volitional'],
  ['抗する', 'imperative'],
  ['甘んじる', 'potential'],
  ['甘んじる', 'passive'],
  ['甘んじる', 'causative'],
  ['甘んじる', 'volitional'],
  ['甘んじる', 'imperative'],
  ['興じる', 'potential'],
  ['興じる', 'passive'],
  ['興じる', 'causative'],
  ['興じる', 'volitional'],
  ['興じる', 'imperative'],
  ['屈する', 'potential'],
  ['屈する', 'passive'],
  ['屈する', 'causative'],
  ['屈する', 'volitional'],
  ['屈する', 'imperative'],
  ['決する', 'potential'],
  ['決する', 'causative'],
  ['決する', 'volitional'],
  ['決する', 'imperative'],
  ['のたうつ', 'potential'],
  ['のたうつ', 'passive'],
  ['のたうつ', 'causative'],
  ['のたうつ', 'volitional'],
  ['のたうつ', 'imperative'],
  ['せめぎ合う', 'passive'],
  ['せめぎ合う', 'causative'],
  ['せめぎ合う', 'volitional'],
  ['せめぎ合う', 'imperative'],
  ['もがく', 'passive'],
  ['もがく', 'causative'],
  ['あがく', 'passive'],
  ['あがく', 'causative'],
  ['ひしめく', 'potential'],
  ['ひしめく', 'passive'],
  ['ひしめく', 'causative'],
  ['ひしめく', 'volitional'],
  ['ひしめく', 'imperative'],
  ['たたずむ', 'passive'],
  ['たたずむ', 'causative'],
  ['たたずむ', 'volitional'],
  ['たたずむ', 'imperative'],
  ['うずくまる', 'passive'],
  ['うずくまる', 'causative'],
  ['はばかる', 'potential'],
  ['はばかる', 'causative'],
  ['はばかる', 'volitional'],
  ['はばかる', 'imperative'],
  ['おもねる', 'potential'],
  ['おもねる', 'passive'],
  ['おもねる', 'causative'],
  ['おもねる', 'volitional'],
  ['おもねる', 'imperative'],
  ['物怖じする', 'potential'],
  ['物怖じする', 'passive'],
  ['物怖じする', 'causative'],
  ['物怖じする', 'volitional'],
  ['物怖じする', 'imperative'],
  ['面食らう', 'potential'],
  ['面食らう', 'passive'],
  ['面食らう', 'volitional'],
  ['面食らう', 'imperative'],
  ['陰る', 'potential'],
  ['陰る', 'passive'],
  ['陰る', 'causative'],
  ['陰る', 'volitional'],
  ['陰る', 'imperative'],
  ['翳む', 'potential'],
  ['翳む', 'passive'],
  ['翳む', 'causative'],
  ['翳む', 'volitional'],
  ['翳む', 'imperative'],
  ['漂わせる', 'passive'],
  ['漂わせる', 'causative'],
  ['染み渡る', 'potential'],
  ['染み渡る', 'passive'],
  ['染み渡る', 'causative'],
  ['染み渡る', 'volitional'],
  ['染み渡る', 'imperative'],
  ['染み入る', 'potential'],
  ['染み入る', 'passive'],
  ['染み入る', 'causative'],
  ['染み入る', 'volitional'],
  ['染み入る', 'imperative'],
  ['打ちひしぐ', 'potential'],
  ['打ちひしぐ', 'causative'],
  ['打ちひしぐ', 'conditional_ba'],
  ['打ちひしぐ', 'conditional_tara'],
  ['打ちひしぐ', 'volitional'],
  ['打ちひしぐ', 'imperative'],
  ['突き動かす', 'causative'],
  ['立ちすくむ', 'potential'],
  ['立ちすくむ', 'passive'],
  ['立ちすくむ', 'causative'],
  ['立ちすくむ', 'volitional'],
  ['立ちすくむ', 'imperative'],
  ['立ち尽くす', 'potential'],
  ['立ち尽くす', 'passive'],
  ['立ち尽くす', 'causative'],
  ['立ち尽くす', 'volitional'],
  ['立ち尽くす', 'imperative'],
  ['立ち竦む', 'potential'],
  ['立ち竦む', 'passive'],
  ['立ち竦む', 'causative'],
  ['立ち竦む', 'volitional'],
  ['立ち竦む', 'imperative'],
  ['言い募る', 'potential'],
  ['言い募る', 'passive'],
  ['言い募る', 'causative'],
  ['言い募る', 'volitional'],
  ['言い募る', 'imperative'],
  ['舐め回す', 'imperative'],
  ['踏み荒らす', 'imperative'],
  ['捻じ曲げる', 'imperative'],
  ['追い縋る', 'potential'],
  ['追い縋る', 'passive'],
  ['追い縋る', 'causative'],
  ['追い縋る', 'volitional'],
  ['追い縋る', 'imperative'],
  ['擲つ', 'potential'],
  ['擲つ', 'causative'],
  ['燻ぶる', 'potential'],
  ['燻ぶる', 'passive'],
  ['燻ぶる', 'causative'],
  ['燻ぶる', 'volitional'],
  ['燻ぶる', 'imperative'],
  ['漲る', 'potential'],
  ['漲る', 'passive'],
  ['漲る', 'causative'],
  ['漲る', 'volitional'],
  ['漲る', 'imperative'],
  ['噴き出す', 'potential'],
  ['噴き出す', 'passive'],
  ['噴き出す', 'causative'],
  ['噴き出す', 'volitional'],
  ['噴き出す', 'imperative'],
  ['溢れ返る', 'potential'],
  ['溢れ返る', 'passive'],
  ['溢れ返る', 'causative'],
  ['溢れ返る', 'volitional'],
  ['溢れ返る', 'imperative'],
  ['湧き上がる', 'potential'],
  ['湧き上がる', 'passive'],
  ['湧き上がる', 'causative'],
  ['湧き上がる', 'volitional'],
  ['湧き上がる', 'imperative'],
  ['沸き立つ', 'potential'],
  ['沸き立つ', 'passive'],
  ['沸き立つ', 'causative'],
  ['沸き立つ', 'volitional'],
  ['沸き立つ', 'imperative'],
  ['渦巻く', 'potential'],
  ['渦巻く', 'passive'],
  ['渦巻く', 'causative'],
  ['渦巻く', 'volitional'],
  ['渦巻く', 'imperative'],
  ['逆巻く', 'potential'],
  ['逆巻く', 'passive'],
  ['逆巻く', 'causative'],
  ['逆巻く', 'volitional'],
  ['逆巻く', 'imperative'],
  ['打ち寄せる', 'potential'],
  ['打ち寄せる', 'passive'],
  ['打ち寄せる', 'causative'],
  ['打ち寄せる', 'volitional'],
  ['打ち寄せる', 'imperative'],
  ['吹き荒れる', 'potential'],
  ['吹き荒れる', 'passive'],
  ['吹き荒れる', 'causative'],
  ['吹き荒れる', 'volitional'],
  ['吹き荒れる', 'imperative'],
  ['降り注ぐ', 'potential'],
  ['降り注ぐ', 'passive'],
  ['降り注ぐ', 'causative'],
  ['降り注ぐ', 'volitional'],
  ['降り注ぐ', 'imperative'],
  ['降り積もる', 'potential'],
  ['降り積もる', 'passive'],
  ['降り積もる', 'causative'],
  ['降り積もる', 'volitional'],
  ['降り積もる', 'imperative'],
  ['照り付ける', 'potential'],
  ['照り付ける', 'passive'],
  ['照り付ける', 'causative'],
  ['照り付ける', 'volitional'],
  ['照り付ける', 'imperative'],
  ['咲き誇る', 'potential'],
  ['咲き誇る', 'passive'],
  ['咲き誇る', 'causative'],
  ['咲き誇る', 'volitional'],
  ['咲き誇る', 'imperative'],
  ['咲き乱れる', 'potential'],
  ['咲き乱れる', 'passive'],
  ['咲き乱れる', 'causative'],
  ['咲き乱れる', 'volitional'],
  ['咲き乱れる', 'imperative'],
  ['生い茂る', 'potential'],
  ['生い茂る', 'passive'],
  ['生い茂る', 'causative'],
  ['生い茂る', 'volitional'],
  ['生い茂る', 'imperative'],
  ['朽ち果てる', 'potential'],
  ['朽ち果てる', 'passive'],
  ['朽ち果てる', 'causative'],
  ['朽ち果てる', 'volitional'],
  ['朽ち果てる', 'imperative'],
  ['打ち捨てる', 'causative'],
  ['荒れ果てる', 'potential'],
  ['荒れ果てる', 'passive'],
  ['荒れ果てる', 'causative'],
  ['荒れ果てる', 'volitional'],
  ['荒れ果てる', 'imperative'],
  ['織り成す', 'potential'],
  ['織り成す', 'causative'],
  ['織り成す', 'volitional'],
  ['織り成す', 'imperative'],
  ['紡ぎ出す', 'causative'],
  ['語り尽くす', 'causative'],
  ['取り成す', 'causative'],
  ['取り成す', 'volitional'],
  ['取り成す', 'imperative'],
  ['取り澄ます', 'potential'],
  ['取り澄ます', 'passive'],
  ['取り澄ます', 'causative'],
  ['取り澄ます', 'volitional'],
  ['取り澄ます', 'imperative'],
  ['居直る', 'potential'],
  ['居直る', 'passive'],
  ['居直る', 'causative'],
  ['居直る', 'volitional'],
  ['居直る', 'imperative'],
  ['開き直る', 'potential'],
  ['開き直る', 'passive'],
  ['開き直る', 'causative'],
  ['開き直る', 'volitional'],
  ['開き直る', 'imperative'],
  ['敷衍する', 'volitional'],
  ['敷衍する', 'imperative'],
  ['紛糾する', 'potential'],
  ['紛糾する', 'passive'],
  ['紛糾する', 'causative'],
  ['紛糾する', 'volitional'],
  ['紛糾する', 'imperative'],
  ['尻拭いする', 'volitional'],
  ['尻拭いする', 'imperative'],
  ['紆余曲折する', 'potential'],
  ['紆余曲折する', 'passive'],
  ['紆余曲折する', 'causative'],
  ['紆余曲折する', 'volitional'],
  ['紆余曲折する', 'imperative'],
  ['一蹴する', 'causative'],
  ['一蹴する', 'volitional'],
  ['一蹴する', 'imperative'],
  ['一変する', 'potential'],
  ['一変する', 'passive'],
  ['一変する', 'volitional'],
  ['一変する', 'imperative'],
  ['一転する', 'potential'],
  ['一転する', 'passive'],
  ['一転する', 'volitional'],
  ['一転する', 'imperative'],
  ['凌辱する', 'potential'],
  ['凌辱する', 'causative'],
  ['凌辱する', 'volitional'],
  ['凌辱する', 'imperative'],
  ['寿ぐ', 'potential'],
  ['寿ぐ', 'causative'],
  ['寿ぐ', 'imperative'],
  ['慶ぶ', 'potential'],
  ['慶ぶ', 'passive'],
  ['慶ぶ', 'causative'],
  ['慶ぶ', 'imperative'],
  ['詣でる', 'passive'],
  ['詣でる', 'imperative'],
  ['嗜む', 'passive'],
  ['嗜む', 'causative'],
  ['嗜む', 'imperative'],
  ['嗜める', 'causative'],
  ['嗜める', 'volitional'],
  ['嗜める', 'imperative'],
  ['綻ぶ', 'potential'],
  ['綻ぶ', 'passive'],
  ['綻ぶ', 'causative'],
  ['綻ぶ', 'volitional'],
  ['綻ぶ', 'imperative'],
  ['佇む', 'potential'],
  ['佇む', 'passive'],
  ['佇む', 'causative'],
  ['佇む', 'volitional'],
  ['佇む', 'imperative'],
  ['窺い知る', 'causative'],
  ['窺い知る', 'volitional'],
  ['窺い知る', 'imperative'],
  ['垣間見る', 'causative'],
  ['垣間見る', 'volitional'],
  ['垣間見る', 'imperative'],
  ['腐心する', 'potential'],
  ['腐心する', 'passive'],
  ['腐心する', 'causative'],
  ['腐心する', 'volitional'],
  ['腐心する', 'imperative'],
  ['苦慮する', 'potential'],
  ['苦慮する', 'passive'],
  ['苦慮する', 'causative'],
  ['苦慮する', 'volitional'],
  ['苦慮する', 'imperative'],
  ['奮闘する', 'potential'],
  ['奮闘する', 'passive'],
  ['奮闘する', 'causative'],
  ['邁進する', 'potential'],
  ['邁進する', 'passive'],
  ['邁進する', 'causative'],
  ['精進する', 'potential'],
  ['精進する', 'passive'],
  ['精進する', 'causative'],
  ['研鑽する', 'potential'],
  ['研鑽する', 'passive'],
  ['研鑽する', 'causative'],
  ['拝察する', 'nai'],
  ['拝察する', 'potential'],
  ['拝察する', 'passive'],
  ['拝察する', 'causative'],
  ['拝察する', 'volitional'],
  ['拝察する', 'imperative'],
  ['恐懼する', 'nai'],
  ['恐懼する', 'potential'],
  ['恐懼する', 'passive'],
  ['恐懼する', 'causative'],
  ['恐懼する', 'volitional'],
  ['恐懼する', 'imperative'],
  ['慶賀する', 'nai'],
  ['慶賀する', 'potential'],
  ['慶賀する', 'causative'],
  ['慶賀する', 'volitional'],
  ['慶賀する', 'imperative'],
  ['拝謁する', 'nai'],
  ['拝謁する', 'potential'],
  ['拝謁する', 'passive'],
  ['拝謁する', 'causative'],
  ['拝謁する', 'volitional'],
  ['拝謁する', 'imperative'],
  ['憂慮する', 'potential'],
  ['憂慮する', 'causative'],
  ['憂慮する', 'volitional'],
  ['憂慮する', 'imperative'],
  ['哀悼する', 'nai'],
  ['哀悼する', 'potential'],
  ['哀悼する', 'causative'],
  ['哀悼する', 'volitional'],
  ['哀悼する', 'imperative'],
  ['追悼する', 'potential'],
  ['追悼する', 'causative'],
  ['追悼する', 'imperative'],
  ['称賛する', 'imperative'],
  ['糾弾する', 'causative'],
  ['弾劾する', 'causative'],
  ['弾劾する', 'volitional'],
  ['弾劾する', 'imperative'],
  ['恫喝する', 'potential'],
  ['恫喝する', 'causative'],
  ['恫喝する', 'volitional'],
  ['恫喝する', 'imperative'],
  ['威嚇する', 'potential'],
  ['威嚇する', 'causative'],
  ['威嚇する', 'volitional'],
  ['威嚇する', 'imperative'],
  ['懐柔する', 'causative'],
  ['懐柔する', 'volitional'],
  ['懐柔する', 'imperative'],
  ['籠絡する', 'potential'],
  ['籠絡する', 'causative'],
  ['籠絡する', 'volitional'],
  ['籠絡する', 'imperative'],
  ['扇動する', 'potential'],
  ['扇動する', 'causative'],
  ['扇動する', 'volitional'],
  ['扇動する', 'imperative'],
  ['教唆する', 'potential'],
  ['教唆する', 'causative'],
  ['教唆する', 'volitional'],
  ['教唆する', 'imperative'],
  ['凌駕する', 'causative'],
  ['凌駕する', 'imperative'],
  ['席巻する', 'causative'],
  ['席巻する', 'volitional'],
  ['席巻する', 'imperative'],
  ['蔓延する', 'potential'],
  ['蔓延する', 'passive'],
  ['蔓延する', 'volitional'],
  ['蔓延する', 'imperative'],
  ['粛清する', 'potential'],
  ['粛清する', 'causative'],
  ['粛清する', 'volitional'],
  ['粛清する', 'imperative'],
  ['瓦解する', 'potential'],
  ['瓦解する', 'passive'],
  ['瓦解する', 'causative'],
  ['瓦解する', 'volitional'],
  ['瓦解する', 'imperative'],
  ['離散する', 'potential'],
  ['離散する', 'passive'],
  ['離散する', 'volitional'],
  ['離散する', 'imperative'],
  ['流浪する', 'potential'],
  ['流浪する', 'passive'],
  ['流浪する', 'causative'],
  ['流浪する', 'volitional'],
  ['流浪する', 'imperative'],
  ['漂泊する', 'potential'],
  ['漂泊する', 'passive'],
  ['漂泊する', 'causative'],
  ['漂泊する', 'volitional'],
  ['漂泊する', 'imperative'],
  ['放浪する', 'potential'],
  ['放浪する', 'passive'],
  ['放浪する', 'causative'],
  ['放浪する', 'imperative'],
  ['逃亡する', 'potential'],
  ['逃亡する', 'passive'],
  ['逃亡する', 'volitional'],
  ['逃亡する', 'imperative'],
  ['亡命する', 'potential'],
  ['亡命する', 'passive'],
  ['亡命する', 'volitional'],
  ['亡命する', 'imperative'],
  ['帰還する', 'passive'],
  ['帰還する', 'imperative'],
  ['凱旋する', 'potential'],
  ['凱旋する', 'passive'],
  ['凱旋する', 'causative'],
  ['凱旋する', 'imperative'],
  ['即位する', 'potential'],
  ['即位する', 'passive'],
  ['即位する', 'volitional'],
  ['即位する', 'imperative'],
  ['退位する', 'potential'],
  ['退位する', 'passive'],
  ['退位する', 'volitional'],
  ['退位する', 'imperative'],
  ['践祚する', 'nai'],
  ['践祚する', 'potential'],
  ['践祚する', 'passive'],
  ['践祚する', 'causative'],
  ['践祚する', 'volitional'],
  ['践祚する', 'imperative'],
  ['布告する', 'potential'],
  ['布告する', 'causative'],
  ['布告する', 'volitional'],
  ['布告する', 'imperative'],
  ['発布する', 'potential'],
  ['発布する', 'causative'],
  ['発布する', 'volitional'],
  ['発布する', 'imperative'],
  ['批准する', 'causative'],
  ['批准する', 'volitional'],
  ['批准する', 'imperative'],
  ['締結する', 'causative'],
  ['締結する', 'volitional'],
  ['締結する', 'imperative'],
  ['調停する', 'causative'],
  ['調停する', 'volitional'],
  ['調停する', 'imperative'],
  ['仲裁する', 'causative'],
  ['仲裁する', 'volitional'],
  ['仲裁する', 'imperative'],
  ['裁定する', 'causative'],
  ['裁定する', 'volitional'],
  ['裁定する', 'imperative'],
  ['制裁する', 'causative'],
  ['制裁する', 'volitional'],
  ['制裁する', 'imperative'],
  ['報復する', 'potential'],
  ['報復する', 'causative'],
  ['報復する', 'volitional'],
  ['報復する', 'imperative'],
  ['応酬する', 'potential'],
  ['応酬する', 'passive'],
  ['応酬する', 'causative'],
  ['応酬する', 'volitional'],
  ['応酬する', 'imperative'],
  ['牽制する', 'causative'],
  ['牽制する', 'volitional'],
  ['牽制する', 'imperative'],
  ['包囲する', 'causative'],
  ['侵攻する', 'potential'],
  ['侵攻する', 'causative'],
  ['侵攻する', 'volitional'],
  ['侵攻する', 'imperative'],
  ['占拠する', 'causative'],
  ['占拠する', 'volitional'],
  ['占拠する', 'imperative'],
  ['陥落する', 'potential'],
  ['陥落する', 'passive'],
  ['陥落する', 'causative'],
  ['陥落する', 'volitional'],
  ['陥落する', 'imperative'],
  ['降伏する', 'potential'],
  ['降伏する', 'passive'],
  ['降伏する', 'imperative'],
  ['投降する', 'potential'],
  ['投降する', 'passive'],
  ['投降する', 'imperative'],
  ['休戦する', 'potential'],
  ['休戦する', 'passive'],
  ['休戦する', 'causative'],
  ['休戦する', 'imperative'],
  ['停戦する', 'potential'],
  ['停戦する', 'passive'],
  ['停戦する', 'imperative'],
  ['講和する', 'potential'],
  ['講和する', 'passive'],
  ['講和する', 'causative'],
  ['講和する', 'imperative'],
  ['復興する', 'imperative'],
  ['興隆する', 'potential'],
  ['興隆する', 'passive'],
  ['興隆する', 'volitional'],
  ['興隆する', 'imperative'],
  ['繁栄する', 'potential'],
  ['繁栄する', 'passive'],
  ['繁栄する', 'volitional'],
  ['繁栄する', 'imperative'],
  ['衰亡する', 'potential'],
  ['衰亡する', 'passive'],
  ['衰亡する', 'causative'],
  ['衰亡する', 'volitional'],
  ['衰亡する', 'imperative'],
  ['滅亡する', 'potential'],
  ['滅亡する', 'passive'],
  ['滅亡する', 'volitional'],
  ['滅亡する', 'imperative'],
  ['勃興する', 'potential'],
  ['勃興する', 'passive'],
  ['勃興する', 'causative'],
  ['勃興する', 'volitional'],
  ['勃興する', 'imperative'],
  ['台頭する', 'potential'],
  ['台頭する', 'passive'],
  ['台頭する', 'causative'],
  ['台頭する', 'volitional'],
  ['台頭する', 'imperative'],
  ['君臨する', 'potential'],
  ['君臨する', 'passive'],
  ['君臨する', 'causative'],
  ['君臨する', 'volitional'],
  ['君臨する', 'imperative'],
  ['統治する', 'causative'],
  ['統治する', 'volitional'],
  ['統治する', 'imperative'],
  ['転落する', 'potential'],
  ['転落する', 'passive'],
  ['転落する', 'causative'],
  ['転落する', 'volitional'],
  ['転落する', 'imperative'],
  ['没落する', 'potential'],
  ['没落する', 'passive'],
  ['没落する', 'causative'],
  ['没落する', 'volitional'],
  ['没落する', 'imperative'],
  ['零落する', 'potential'],
  ['零落する', 'passive'],
  ['零落する', 'causative'],
  ['零落する', 'volitional'],
  ['零落する', 'imperative'],
  ['専横する', 'potential'],
  ['専横する', 'passive'],
  ['専横する', 'causative'],
  ['専横する', 'volitional'],
  ['専横する', 'imperative'],
  ['壟断する', 'potential'],
  ['壟断する', 'causative'],
  ['壟断する', 'volitional'],
  ['壟断する', 'imperative'],
  ['搾取する', 'potential'],
  ['搾取する', 'causative'],
  ['搾取する', 'volitional'],
  ['搾取する', 'imperative'],
  ['収奪する', 'potential'],
  ['収奪する', 'causative'],
  ['収奪する', 'volitional'],
  ['収奪する', 'imperative'],
  ['蹂躙する', 'potential'],
  ['蹂躙する', 'causative'],
  ['蹂躙する', 'volitional'],
  ['蹂躙する', 'imperative'],
  ['征伐する', 'potential'],
  ['征伐する', 'causative'],
  ['征伐する', 'volitional'],
  ['征伐する', 'imperative'],
  ['討伐する', 'potential'],
  ['討伐する', 'causative'],
  ['討伐する', 'volitional'],
  ['討伐する', 'imperative'],
  ['掃討する', 'potential'],
  ['掃討する', 'causative'],
  ['掃討する', 'volitional'],
  ['掃討する', 'imperative'],
  ['殲滅する', 'potential'],
  ['殲滅する', 'causative'],
  ['殲滅する', 'volitional'],
  ['殲滅する', 'imperative'],
  ['蜂起する', 'potential'],
  ['蜂起する', 'passive'],
  ['蜂起する', 'causative'],
  ['蜂起する', 'imperative'],
  ['決起する', 'potential'],
  ['決起する', 'passive'],
  ['決起する', 'causative'],
  ['決起する', 'imperative'],
  ['挙兵する', 'potential'],
  ['挙兵する', 'passive'],
  ['挙兵する', 'causative'],
  ['挙兵する', 'imperative'],
  ['謀反する', 'potential'],
  ['謀反する', 'passive'],
  ['謀反する', 'causative'],
  ['謀反する', 'volitional'],
  ['謀反する', 'imperative'],
  ['潰走する', 'potential'],
  ['潰走する', 'passive'],
  ['潰走する', 'causative'],
  ['潰走する', 'volitional'],
  ['潰走する', 'imperative'],
  ['撤退する', 'potential'],
  ['撤退する', 'passive'],
  ['撤退する', 'imperative'],
  ['進軍する', 'potential'],
  ['進軍する', 'passive'],
  ['進軍する', 'imperative'],
  ['奇襲する', 'potential'],
  ['奇襲する', 'causative'],
  ['奇襲する', 'volitional'],
  ['奇襲する', 'imperative'],
  ['強襲する', 'potential'],
  ['強襲する', 'causative'],
  ['強襲する', 'volitional'],
  ['強襲する', 'imperative'],
  ['攻略する', 'causative'],
  ['略奪する', 'potential'],
  ['略奪する', 'causative'],
  ['略奪する', 'volitional'],
  ['略奪する', 'imperative'],
  ['虐殺する', 'potential'],
  ['虐殺する', 'causative'],
  ['虐殺する', 'volitional'],
  ['虐殺する', 'imperative'],
  ['追放する', 'causative'],
  ['追放する', 'volitional'],
  ['追放する', 'imperative'],
  ['幽閉する', 'potential'],
  ['幽閉する', 'causative'],
  ['幽閉する', 'volitional'],
  ['幽閉する', 'imperative'],
  ['処刑する', 'potential'],
  ['処刑する', 'causative'],
  ['処刑する', 'volitional'],
  ['処刑する', 'imperative'],
  ['恩赦する', 'potential'],
  ['恩赦する', 'causative'],
  ['恩赦する', 'volitional'],
  ['恩赦する', 'imperative'],
  ['赦免する', 'potential'],
  ['赦免する', 'causative'],
  ['赦免する', 'volitional'],
  ['赦免する', 'imperative'],
  ['懐古する', 'potential'],
  ['懐古する', 'passive'],
  ['懐古する', 'causative'],
  ['懐古する', 'volitional'],
  ['懐古する', 'imperative'],
  ['回顧する', 'potential'],
  ['回顧する', 'causative'],
  ['回顧する', 'volitional'],
  ['回顧する', 'imperative'],
  ['慈しむ', 'causative'],
  ['慈しむ', 'imperative'],
  ['労わる', 'causative'],
  ['奉る', 'potential'],
  ['奉る', 'causative'],
  ['奉る', 'imperative'],
  ['祀る', 'potential'],
  ['祀る', 'causative'],
  ['祀る', 'volitional'],
  ['祀る', 'imperative'],
  ['弔う', 'potential'],
  ['弔う', 'causative'],
  ['弔う', 'imperative'],
  ['偲ぶ', 'potential'],
  ['偲ぶ', 'causative'],
  ['偲ぶ', 'imperative'],
  ['悼む', 'potential'],
  ['悼む', 'causative'],
  ['悼む', 'volitional'],
  ['悼む', 'imperative'],
  ['堪え忍ぶ', 'passive'],
  ['堪え忍ぶ', 'causative'],
  ['堪え忍ぶ', 'imperative'],
  ['思い悩む', 'potential'],
  ['思い悩む', 'passive'],
  ['思い悩む', 'volitional'],
  ['思い悩む', 'imperative'],
  ['思い焦がれる', 'potential'],
  ['思い焦がれる', 'passive'],
  ['思い焦がれる', 'causative'],
  ['思い焦がれる', 'volitional'],
  ['思い焦がれる', 'imperative'],
  ['思い馳せる', 'potential'],
  ['思い馳せる', 'passive'],
  ['思い馳せる', 'causative'],
  ['思い馳せる', 'imperative'],
  ['思い詰める', 'potential'],
  ['思い詰める', 'passive'],
  ['思い詰める', 'causative'],
  ['思い詰める', 'volitional'],
  ['思い詰める', 'imperative'],
  ['思い煩う', 'potential'],
  ['思い煩う', 'passive'],
  ['思い煩う', 'causative'],
  ['思い煩う', 'volitional'],
  ['思い煩う', 'imperative'],
  ['思い残す', 'masu'],
  ['思い残す', 'potential'],
  ['思い残す', 'passive'],
  ['思い残す', 'causative'],
  ['思い残す', 'volitional'],
  ['思い残す', 'imperative'],
  ['思い定める', 'potential'],
  ['思い定める', 'passive'],
  ['思い定める', 'causative'],
  ['思い定める', 'imperative'],
  ['紐解く', 'causative'],
  ['紐解く', 'imperative'],
  ['錆び付く', 'potential'],
  ['錆び付く', 'passive'],
  ['錆び付く', 'causative'],
  ['錆び付く', 'volitional'],
  ['錆び付く', 'imperative'],
  ['暗中模索する', 'potential'],
  ['暗中模索する', 'passive'],
  ['暗中模索する', 'causative'],
  ['暗中模索する', 'volitional'],
  ['暗中模索する', 'imperative'],
  ['試行錯誤する', 'potential'],
  ['試行錯誤する', 'passive'],
  ['試行錯誤する', 'causative'],
  ['試行錯誤する', 'imperative'],
  ['臥薪嘗胆する', 'potential'],
  ['臥薪嘗胆する', 'passive'],
  ['臥薪嘗胆する', 'causative'],
  ['臥薪嘗胆する', 'imperative'],
  ['呉越同舟する', 'potential'],
  ['呉越同舟する', 'passive'],
  ['呉越同舟する', 'causative'],
  ['呉越同舟する', 'volitional'],
  ['呉越同舟する', 'imperative'],
  ['瞑る', 'passive'],
  ['瞑る', 'causative'],
  ['噤む', 'potential'],
  ['噤む', 'passive'],
  ['噤む', 'causative'],
  ['分かつ', 'potential'],
  ['分かつ', 'causative'],
  ['分かつ', 'conditional_tara'],
  ['分かつ', 'volitional'],
  ['分かつ', 'imperative'],
  ['きたす', 'potential'],
  ['きたす', 'passive'],
  ['きたす', 'causative'],
  ['きたす', 'volitional'],
  ['きたす', 'imperative'],
];

describe('N1 form example sentences', () => {
  const entries: [string, ConjugationForm, string][] = [];
  for (const [verb, forms] of Object.entries(n1dataset)) {
    for (const [form, sentence] of Object.entries(forms)) {
      entries.push([verb, form as ConjugationForm, sentence as string]);
    }
  }

  it('covers a non-trivial number of sentences', () => {
    expect(entries.length).toBeGreaterThan(4000);
  });

  it('covers every N1 verb', () => {
    const n1Verbs = Object.entries(verbs).filter(([, d]) => d.jlpt === 'N1').map(([v]) => v);
    expect(new Set(Object.keys(n1dataset))).toEqual(new Set(n1Verbs));
  });

  it('matches the expected count by form', () => {
    const counts: Partial<Record<ConjugationForm, number>> = {};
    for (const [, form] of entries) {
      counts[form] = (counts[form] || 0) + 1;
    }
    expect(counts).toEqual(n1ExpectedCountsByForm);
  });

  it('only references N1 verbs that exist', () => {
    for (const verb of Object.keys(n1dataset)) {
      expect(verbs[verb]).toBeDefined();
      expect(verbs[verb].jlpt).toBe('N1');
    }
  });

  it('each sentence contains its exact conjugated form (kanji or kana)', () => {
    const offenders: string[] = [];
    for (const [verb, form, sentence] of entries) {
      const data = verbs[verb];
      const kanji = conjugate(verb, data, form).value;
      const kana = conjugateReading(data, form);
      if (!sentence.includes(kanji) && !sentence.includes(kana)) {
        offenders.push(`${verb}:${form} -> "${sentence}" (expected ${kanji}/${kana})`);
      }
    }
    expect(offenders).toEqual([]);
  });

  it('generates no examples for N1 excludeForms forms', () => {
    expectExcludedFormsAbsent('N1', n1dataset);
  });

  it('omits only intentional non-exclude N1 forms', () => {
    expect(nonExcludeOmissions('N1', n1dataset)).toEqual(n1IntentionalOmissions);
  });
});
